// Literary/film examples — a real, well-known work mapped beat-by-beat onto one structure, or
// act-by-act onto one plot type, so you can see how a familiar story actually fills in the shape.
// Each example is tied to exactly one structure OR one plot type (appliesToType/appliesToId);
// `beats` keys match that structure's beat ids (or, for a plot type, the four shared act keys).
export const EXAMPLES = [
  {
    id: "star-wars-hero-journey",
    title: "Star Wars: A New Hope",
    creator: "George Lucas, 1977",
    appliesToType: "structure",
    appliesToId: "hero-journey",
    beats: {
      "ordinary-world": "Luke Skywalker lives a dull life as a moisture farmer on Tatooine, dreaming of something more.",
      "call": "R2-D2 carries Princess Leia's hidden message asking for Obi-Wan Kenobi's help.",
      "refusal": "Luke tells Obi-Wan he can't leave — his uncle needs him on the farm.",
      "mentor": "Obi-Wan gives Luke his father's lightsaber and begins teaching him about the Force.",
      "threshold": "Luke finds his aunt and uncle killed and commits to leaving Tatooine for good.",
      "tests-allies": "Luke meets Han Solo and Chewbacca in Mos Eisley and hires the Millennium Falcon.",
      "approach": "The crew is captured by the Death Star's tractor beam and plans a rescue.",
      "ordeal": "Luke and friends rescue Leia and narrowly escape the trash compactor.",
      "reward": "They escape the Death Star with Leia and the stolen plans — but Obi-Wan is struck down by Vader.",
      "road-back": "The Millennium Falcon is pursued back to the Rebel base, secretly tracked by the Empire.",
      "resurrection": "Luke joins the assault on the Death Star, using the Force instead of his targeting computer.",
      "elixir": "Luke destroys the Death Star and is honored as a hero of the Rebellion.",
    },
  },
  {
    id: "die-hard-three-act",
    title: "Die Hard",
    creator: "screenplay by Jeb Stuart & Steven E. de Souza, 1988",
    appliesToType: "structure",
    appliesToId: "three-act",
    beats: {
      "status-quo": "John McClane arrives in LA for Christmas, estranged from his wife Holly, and heads to her office party at Nakatomi Plaza.",
      "inciting": "Terrorists led by Hans Gruber seize the building and take everyone hostage — McClane escapes upstairs, barefoot.",
      "plot-point-1": "McClane triggers the fire alarm and grabs a fire axe, committing to fight back alone and unarmed.",
      "rising": "McClane befriends Sgt. Al Powell by radio and starts picking off Gruber's men one by one to arm himself.",
      "midpoint": "McClane discovers Gruber's plan isn't terrorism at all — it's a $640 million vault heist hidden behind a hostage crisis.",
      "plot-point-2": "The FBI's assault plan fails catastrophically, and McClane is nearly killed running barefoot across broken glass.",
      "climax": "McClane confronts Gruber directly, ending with Gruber falling from the tower as McClane frees Holly's watch-clasped hand.",
      "resolution": "McClane and Holly reunite outside, reconciled, as the hostages are freed and the police stand down.",
    },
  },
  {
    id: "legally-blonde-save-the-cat",
    title: "Legally Blonde",
    creator: "screenplay by Karen McCullah & Kirsten Smith, 2001",
    appliesToType: "structure",
    appliesToId: "save-the-cat",
    beats: {
      "opening-image": "Elle Woods prepares for what she assumes will be a marriage proposal from her boyfriend Warner.",
      "theme-stated": "A sorority sister tells Elle looks aren't everything — foreshadowing that she'll have to prove her substance.",
      "set-up": "Elle is shown as popular and fashion-obsessed, and academically underestimated by everyone around her.",
      "catalyst": "Warner breaks up with Elle, saying he needs someone more 'serious' for law school and his future.",
      "debate": "Elle wonders whether to chase Warner to Harvard Law or accept the breakup and move on.",
      "break-into-two": "Elle throws herself into studying and gets into Harvard Law School to win Warner back.",
      "b-story": "Elle meets Emmett, a working-class law associate who sees her potential when no one else does.",
      "fun-and-games": "Elle clashes with Harvard's elitist culture — mocked and out of place in her pink outfits.",
      "midpoint": "Elle lands a coveted internship on a real murder case, despite everyone's low expectations of her.",
      "bad-guys-close": "Professor Callahan makes an inappropriate advance, shaking Elle's confidence and trust badly.",
      "all-is-lost": "Elle nearly quits law school entirely, packing to go home in defeat.",
      "dark-night": "Elle's mentor Paulette and her friends convince her she's more capable than she's giving herself credit for.",
      "break-into-three": "Elle returns with new resolve, drawing on real expertise — including her knowledge of hair perms — to solve the case.",
      "finale": "Elle cross-examines the witness and proves the case using knowledge no one else in the room has.",
      "final-image": "Elle graduates at the top of her class and gives the commencement speech, respected on her own terms.",
    },
  },
  {
    id: "jaws-overcoming-monster",
    title: "Jaws",
    creator: "Peter Benchley / dir. Steven Spielberg, 1975",
    appliesToType: "plotType",
    appliesToId: "overcoming-monster",
    beats: {
      setup: "A great white shark begins attacking swimmers off Amity Island, and Chief Brody wants to close the beaches.",
      rise: "Brody, Hooper and Quint set out on the Orca to hunt the shark, which proves far larger and smarter than expected.",
      climax: "The shark destroys the boat and attacks the crew directly, cornering Brody alone.",
      fall: "Brody kills the shark by shooting a pressurized tank in its mouth, and swims back to shore.",
    },
  },
  {
    id: "alice-voyage-return",
    title: "Alice's Adventures in Wonderland",
    creator: "Lewis Carroll, 1865",
    appliesToType: "plotType",
    appliesToId: "voyage-and-return",
    beats: {
      setup: "Alice follows a white rabbit down a hole into the strange, rule-bending world of Wonderland.",
      rise: "She explores Wonderland's oddities — shrinking, growing, tea parties, talking creatures — delighted and increasingly disoriented.",
      climax: "The Queen of Hearts turns violently dangerous, putting Alice on trial and threatening her life.",
      fall: "Alice asserts herself against the Queen's tyranny and wakes up back home, the whole adventure behind her.",
    },
  },
  {
    id: "macbeth-tragedy",
    title: "Macbeth",
    creator: "William Shakespeare, c. 1606",
    appliesToType: "plotType",
    appliesToId: "tragedy",
    beats: {
      setup: "Macbeth, a loyal and celebrated general, is told by three witches that he will become king.",
      rise: "Ambition and his wife's urging push Macbeth to murder King Duncan and seize the throne.",
      climax: "Macbeth's paranoia drives him to murder more and more to secure his rule, including his friend Banquo.",
      fall: "Macbeth's tyranny collapses under rebellion; he is killed by Macduff, his ambition having cost him everything.",
    },
  },
  {
    id: "cinderella-rags-to-riches",
    title: "Cinderella",
    creator: "traditional folk tale",
    appliesToType: "plotType",
    appliesToId: "rags-to-riches",
    beats: {
      setup: "Cinderella is overworked and mistreated by her stepmother and stepsisters, denied any life of her own.",
      rise: "With her fairy godmother's help, she attends the royal ball and catches the Prince's attention — then flees at midnight, losing a glass slipper.",
      climax: "The Prince's search for the slipper's owner puts Cinderella's fate in the hands of a single, decisive test.",
      fall: "The slipper fits; Cinderella marries the Prince, her worth finally recognized beyond her circumstances.",
    },
  },

  // ===== structure examples (remaining 14) =====
  {
    id: "romeo-juliet-freytag",
    title: "Romeo and Juliet",
    creator: "William Shakespeare, c. 1595",
    appliesToType: "structure",
    appliesToId: "freytag",
    beats: {
      exposition: "The Montagues and Capulets are introduced as two feuding Verona families, and Romeo and Juliet meet and fall in love at the Capulet ball.",
      "rising-action": "The two marry in secret, but Romeo kills Juliet's cousin Tybalt in a duel and is banished from Verona.",
      climax: "Juliet fakes her death with a friar's potion to avoid a forced marriage, planning to reunite with Romeo once he's told the truth.",
      "falling-action": "The message explaining the plan never reaches Romeo, who hears only that Juliet is dead.",
      denouement: "Romeo kills himself at her tomb; Juliet wakes and, finding him dead, kills herself too — their deaths finally reconciling the two families.",
    },
  },
  {
    id: "hunger-games-seven-point",
    title: "The Hunger Games",
    creator: "Suzanne Collins, 2008",
    appliesToType: "structure",
    appliesToId: "seven-point",
    beats: {
      hook: "Katniss Everdeen lives in poverty in District 12, providing for her family by illegally hunting outside the fence.",
      "plot-turn-1": "Katniss volunteers to take her younger sister's place in the deadly Hunger Games, and is taken to the Capitol to train.",
      "pinch-1": "The Games begin, and the Career tributes' brutal alliance shows Katniss exactly how outmatched she is.",
      midpoint: "Katniss allies with Rue and, after Rue's death, openly defies the Capitol by honoring her — shifting from survival to resistance.",
      "pinch-2": "The Gamemakers change the rules and then reverse them again, forcing a final, desperate confrontation.",
      "plot-turn-2": "Katniss and Peeta realize the only way to beat the Capitol's game is to threaten to deny it a winner at all.",
      resolution: "Both are declared victors, but Katniss's act of defiance has marked her as a target of the Capitol's attention.",
    },
  },
  {
    id: "gift-of-magi-kishotenketsu",
    title: "The Gift of the Magi",
    creator: "O. Henry, 1905",
    appliesToType: "structure",
    appliesToId: "kishotenketsu",
    beats: {
      ki: "Della, poor and married to Jim, wants desperately to buy him a worthy Christmas gift.",
      sho: "She sells her one great beauty — her long hair — to buy Jim a chain for his prized pocket watch.",
      ten: "Jim arrives home having sold his own great possession, the watch, to buy Della the combs she'd always wanted for her hair.",
      ketsu: "Their gifts are now useless, but the story recasts this loss as proof of a love greater than anything money could buy.",
    },
  },
  {
    id: "alien-fichtean",
    title: "Alien",
    creator: "dir. Ridley Scott, 1979",
    appliesToType: "structure",
    appliesToId: "fichtean",
    beats: {
      "crisis-1": "The crew of the Nostromo investigates a distress signal and brings an unknown lifeform aboard, already deep into danger.",
      "crisis-2": "The creature attacks and kills a crew member, and the crew realizes it's grown far larger and more dangerous than first seen.",
      "crisis-3": "The crew's attempts to trap and kill the alien fail one after another, and it picks them off through the ship's vents.",
      "crisis-4": "Ripley discovers the science officer Ash is an android under orders to protect the alien over the crew's lives.",
      climax: "Ripley triggers the ship's self-destruct and flees to the escape shuttle, only to find the alien has stowed away with her.",
      resolution: "Ripley blasts the creature out of the airlock and drifts alone in the shuttle, the sole survivor.",
    },
  },
  {
    id: "finding-nemo-story-circle",
    title: "Finding Nemo",
    creator: "Pixar, dir. Andrew Stanton, 2003",
    appliesToType: "structure",
    appliesToId: "story-circle",
    beats: {
      you: "Marlin, an anxious clownfish, is overly protective of his only son Nemo after losing his wife and other children.",
      need: "Nemo wants independence and to prove himself, defying Marlin's caution.",
      go: "Nemo is captured by a diver and taken away, forcing Marlin to leave the reef for the first time to find him.",
      search: "Marlin, with Dory's help, searches the ocean, facing sharks, jellyfish and the vast unknown.",
      find: "Marlin locates the fish tank in Sydney where Nemo is being held, having grown along the way.",
      take: "Marlin nearly loses Dory and himself in the process, and believes at one point that Nemo has died.",
      return: "Nemo escapes the tank and reunites with his father in the ocean.",
      change: "Marlin returns home a less fearful, more trusting father, letting Nemo swim off to school on his own.",
    },
  },
  {
    id: "raiders-eight-sequence",
    title: "Raiders of the Lost Ark",
    creator: "dir. Steven Spielberg, 1981",
    appliesToType: "structure",
    appliesToId: "eight-sequence",
    beats: {
      "status-quo": "Indiana Jones, an archaeologist and adventurer, narrowly retrieves a golden idol from a booby-trapped temple, only to lose it to a rival.",
      predicament: "The U.S. government recruits Indy to find the Ark of the Covenant before the Nazis do.",
      "obstacle-1": "Indy travels to Nepal to recover a medallion needed to locate the Ark, and reunites with his former love, Marion.",
      "stakes-1": "In Cairo, Indy and Marion evade Nazi agents and rival archaeologist Belloq while racing to the Ark's hidden location.",
      midpoint: "Indy finds the Ark first, but Belloq and the Nazis seize it from him at gunpoint.",
      "stakes-2": "Indy and Marion are captured, and the Nazis begin shipping the Ark toward Germany.",
      culmination: "Indy stages a daring commando raid on the Nazi convoy to reclaim the Ark before it can be studied.",
      climax: "The Nazis open the Ark on a remote island, unleashing a wrathful power that destroys everyone who looks upon it except Indy and Marion, who look away.",
    },
  },
  {
    id: "harry-potter-weiland",
    title: "Harry Potter and the Sorcerer's Stone",
    creator: "J.K. Rowling, 1997",
    appliesToType: "structure",
    appliesToId: "weiland",
    beats: {
      hook: "Harry Potter lives a miserable, neglected life with the Dursleys, unaware of his true origins.",
      inciting: "Letters from Hogwarts start arriving, and Hagrid reveals Harry is a wizard.",
      "plot-point-1": "Harry boards the Hogwarts Express and begins his first year at the School of Witchcraft and Wizardry.",
      "pinch-1": "Harry and his friends discover something dangerous is being guarded on the school's forbidden third floor.",
      midpoint: "Harry learns the object is the Sorcerer's Stone, and suspects Professor Snape is trying to steal it for Voldemort.",
      "pinch-2": "Hagrid lets slip the secret to controlling the three-headed guard dog, and the trio realizes the theft is imminent.",
      "plot-point-3": "Harry, Ron and Hermione descend through the trapdoor themselves to stop the theft before it's too late.",
      climax: "Harry confronts Professor Quirrell, who is possessed by Voldemort, and protects the Stone through his mother's protective love.",
      resolution: "Harry recovers from his injuries, Gryffindor wins the house cup, and he returns to the Dursleys for the summer, now knowing who he really is.",
    },
  },
  {
    id: "godfather-truby-22",
    title: "The Godfather",
    creator: "dir. Francis Ford Coppola, 1972",
    appliesToType: "structure",
    appliesToId: "truby-22",
    beats: {
      "self-rev-preview": "Michael Corleone begins the story insisting he wants nothing to do with the family business.",
      ghost: "The Corleone family's violent criminal history shapes the world Michael has tried to distance himself from.",
      weakness: "Michael's need to prove his loyalty and protect his family will pull him back in, despite his own denial.",
      inciting: "Vito Corleone is shot and nearly killed in an assassination attempt by a rival family.",
      desire: "Michael wants to protect his father and stabilize the family without becoming the man his father is.",
      allies: "Michael's brothers Sonny and Fredo, and the family's consigliere Tom Hagen, all play their parts around him.",
      opponent: "Rival mob boss Sollozzo and the corrupt police captain McCluskey threaten the Corleones directly.",
      "fake-ally": "McCluskey poses as a neutral law-enforcement figure while actually protecting Sollozzo.",
      "first-rev": "Michael realizes no one else can get close enough to kill Sollozzo and McCluskey — only he can, precisely because he's seen as harmless.",
      plan: "Michael plans to meet Sollozzo and McCluskey under a truce, with a gun planted in the restaurant bathroom.",
      "opp-plan": "Sollozzo and McCluskey plan the same meeting believing they hold all the power over an unarmed civilian.",
      drive: "Michael commits fully, murdering both men and fleeing to Sicily to avoid the war that follows.",
      "attack-ally": "Sonny's hot temper gets him killed in an ambush, a catastrophic blow struck through the family's own vulnerabilities.",
      "apparent-defeat": "Michael's Sicilian bride is killed by a car bomb meant for him, and the family's war seems to be spiraling out of control.",
      "second-rev": "Michael returns to America harder and more resolved, taking on real control of the family's operations.",
      "audience-rev": "The audience sees Michael's transformation more clearly than his own family does, as he consolidates power while appearing reasonable.",
      "third-rev": "Michael learns exactly which family heads and traitors — including his own brother-in-law — have betrayed the Corleones.",
      gate: "Michael becomes godfather to his nephew, standing in church even as his final plan is set irrevocably in motion.",
      battle: "In a single sequence, Michael's men assassinate the heads of the rival Five Families and settle every old score at once.",
      "self-rev": "Michael has fully become the ruthless don he once swore he'd never be.",
      moral: "He lies to his wife Kay's face about his crimes, choosing the family's code over honesty with her.",
      "new-equilibrium": "The door closes on Kay, now shut out, as Michael takes his place as the new Godfather.",
    },
  },
  {
    id: "lion-king-pixar-spine",
    title: "The Lion King",
    creator: "Disney, dir. Roger Allers & Rob Minkoff, 1994",
    appliesToType: "structure",
    appliesToId: "pixar-spine",
    beats: {
      "once-upon": "Simba is born a lion cub, prince of the Pride Lands, presented to the animal kingdom by his father Mufasa.",
      "every-day": "Simba grows up playful and eager, learning what it means to one day be king.",
      "until-one-day": "Simba's uncle Scar tricks him into a stampede that kills Mufasa, and convinces Simba the death was his fault.",
      "because-1": "Guilt-ridden, Simba flees the Pride Lands and is taken in by Timon and Pumbaa, who teach him to forget his past.",
      "because-2": "Simba grows up in exile until his childhood friend Nala finds him and tells him Scar has ruined the kingdom.",
      "until-finally": "Simba returns, confronts Scar, and reclaims his place as king in a final battle for the Pride Lands.",
      "ever-since": "Simba takes his rightful place as king, and presents his own newborn cub just as his father once presented him.",
    },
  },
  {
    id: "october-sky-virgins-promise",
    title: "October Sky",
    creator: "dir. Joe Johnston, 1999 (based on Homer Hickam's memoir)",
    appliesToType: "structure",
    appliesToId: "virgins-promise",
    beats: {
      "dependent-world": "Homer Hickam lives in a West Virginia coal town where sons are expected to follow their fathers into the mine.",
      price: "Homer's father expects him to take over as mine superintendent, leaving no room for other ambitions.",
      opportunity: "Inspired by the launch of Sputnik, Homer decides to build his own rockets.",
      "dresses-part": "Homer and his friends start experimenting with homemade rockets, learning by failure and explosion.",
      "secret-world": "The boys build increasingly sophisticated rockets in secret, teaching themselves calculus and machining along the way.",
      "no-longer-fits": "Homer's growing passion for rocketry puts him increasingly at odds with his father's expectations for his future.",
      "caught-shining": "A rocket is blamed for starting a forest fire, and the town turns against the boys' project.",
      "gives-up": "Facing his father's disapproval and the town's suspicion, Homer nearly abandons rocketry for good.",
      "ally-helps": "A teacher, Miss Riley, and the boys' own evidence prove their rocket didn't start the fire, keeping the dream alive.",
      "kingdom-chaos": "A mine accident injures Homer's father, throwing the family's future and the town's fate into uncertainty.",
      "chooses-journey": "Homer returns to finish his rocket project and enter the National Science Fair, choosing his own path forward.",
      "rages-reveals": "Homer and his friends present their rocketry work at the science fair, openly proving what they can do.",
      wonder: "They win a national award, and Homer earns a scholarship that leads him, eventually, to a career at NASA.",
    },
  },
  {
    id: "devil-wears-prada-heroines-journey",
    title: "The Devil Wears Prada",
    creator: "dir. David Frankel, 2006 (based on Lauren Weisberger's novel)",
    appliesToType: "structure",
    appliesToId: "heroines-journey",
    beats: {
      separation: "Andy Sachs takes a job at a prestigious fashion magazine, dismissive of the industry's values she doesn't share.",
      identification: "To succeed, she adopts the demanding, image-driven standards of her boss Miranda Priestly and the magazine's world.",
      "road-of-trials": "Andy proves herself through increasingly difficult, high-pressure tasks that Miranda throws at her.",
      boon: "Andy becomes genuinely skilled at the job, trusted with real responsibility and access to a glamorous world.",
      aridity: "Her success costs her relationships with her boyfriend and friends, and she starts to feel like a different, emptier person.",
      descent: "A crisis — betraying a colleague under Miranda's orders — forces Andy to confront what she's become.",
      yearning: "Andy realizes she misses who she was before the job reshaped her values.",
      "healing-split": "She quits the job outright, rejecting the version of success Miranda represents.",
      "healing-masculine": "Andy carries the discipline and confidence she gained into a new, more honest career path.",
      integration: "She reconnects with her old friends and relationships as herself, having kept what served her and let go of what didn't.",
    },
  },
  {
    id: "three-little-pigs-todorov",
    title: "The Three Little Pigs",
    creator: "traditional folk tale",
    appliesToType: "structure",
    appliesToId: "todorov",
    beats: {
      equilibrium: "Three little pigs leave home and each build their own house, living peacefully.",
      disruption: "A wolf arrives and blows down the houses of straw and sticks, eating the first two pigs.",
      recognition: "The third pig, who built with brick, realizes the wolf is a real and serious threat.",
      repair: "The wolf tries to get into the brick house through the chimney, and the pig boils a pot of water to stop him.",
      "new-equilibrium": "The wolf is defeated for good, and the surviving pig lives safely in his sturdy house.",
    },
  },
  {
    id: "frankenstein-frame-narrative",
    title: "Frankenstein",
    creator: "Mary Shelley, 1818",
    appliesToType: "structure",
    appliesToId: "frame-narrative",
    beats: {
      "enter-frame": "Arctic explorer Robert Walton writes letters to his sister describing his voyage, when his ship rescues a stranded, desperate man.",
      "frame-setup": "The rescued man, Victor Frankenstein, agrees to tell Walton the story of how he came to be alone on the ice.",
      "inner-begins": "Victor recounts his obsession with creating life, and the moment his creature first opens its eyes.",
      "inner-develops": "Horrified by what he's made, Victor abandons his creation, which learns, suffers, and turns to vengeance against him.",
      "inner-resolves": "The creature kills those Victor loves one by one, and Victor pursues it into the Arctic to destroy it.",
      "return-frame": "Victor finishes his story to Walton, exhausted and near death from his pursuit.",
      "frame-closes": "Victor dies aboard Walton's ship, and the creature appears one last time, mourning its creator before vanishing into the ice.",
    },
  },
  {
    id: "cinderella-propp-31",
    title: "Cinderella",
    creator: "traditional folk tale",
    appliesToType: "structure",
    appliesToId: "propp-31",
    beats: {
      absentation: "Cinderella's father, her last protector, is often absent or ineffective, leaving her at her stepmother's mercy.",
      interdiction: "The fairy godmother warns Cinderella she must return before midnight, when the magic will end.",
      violation: "Cinderella, swept up in the ball, loses track of time and almost violates the warning.",
      reconnaissance: "The stepmother and stepsisters watch Cinderella closely, suspicious of any spark of hope in her.",
      delivery: "Word arrives of a royal ball where the prince will choose a bride, information the stepfamily hoards for themselves.",
      trickery: "The stepmother promises Cinderella she may attend if she finishes an impossible list of chores, never intending to let her go.",
      complicity: "Cinderella, desperate to belong, believes the promise and works herself to exhaustion trying to earn her place.",
      "villainy-lack": "The stepmother and stepsisters destroy Cinderella's makeshift gown, leaving her with nothing to wear and no way to attend.",
      mediation: "Cinderella's fairy godmother appears, moved by her distress, and resolves to help her get to the ball.",
      counteraction: "Cinderella accepts the fairy godmother's help and agrees to go, despite everything stacked against her.",
      departure: "Transformed and dressed for the ball, Cinderella leaves for the palace in her enchanted coach.",
      "donor-first": "The fairy godmother tests nothing of Cinderella directly, but her sudden appearance is itself the classic donor encounter.",
      "hero-reaction": "Cinderella receives the magical help with gratitude, not entitlement, and promises to return by midnight.",
      "magical-agent": "She's given the coach, the footmen, the gown, and the glass slippers — the tools that make the rest of the story possible.",
      guidance: "The magic carries her directly to the ball, delivering her into the prince's presence.",
      struggle: "Cinderella's real struggle is against the clock itself, racing the enchantment's deadline rather than a person.",
      branding: "In her rush to escape before midnight, she leaves behind a single glass slipper — a mark that will later identify her.",
      victory: "She escapes the palace before the spell breaks and her disguise is exposed, her secret still safe.",
      liquidation: "The immediate crisis — being unmasked as a servant at a royal ball — is avoided, at the cost of losing the prince's trail.",
      return: "Cinderella returns home to her ordinary, mistreated life, the ball already feeling like a dream.",
      pursuit: "The prince, determined to find the woman who fled, sends his men through the kingdom carrying the glass slipper.",
      rescue: "The fairy godmother's earlier intervention is what makes any of this possible — Cinderella's 'rescue' from her drudgery, however brief.",
      unrecognized: "When the prince's men arrive at her house, Cinderella is treated as just another servant, unrecognized as the woman from the ball.",
      unfounded: "Her stepsisters try to force their feet into the glass slipper, each falsely claiming they are the one the prince seeks.",
      "difficult-task": "Every woman in the kingdom must try on the glass slipper to prove she's the one who fits it.",
      solution: "Only Cinderella's foot fits the slipper perfectly, when she's finally given the chance to try.",
      "propp-recognition": "The prince recognizes her as the woman from the ball, slipper and all.",
      exposure: "The stepsisters' false claims are exposed as the slipper reveals who the real match is.",
      transfiguration: "Cinderella is dressed properly at last, presented as a bride rather than a servant.",
      punishment: "The stepmother and stepsisters lose their hold over Cinderella entirely, cast out of her new life.",
      wedding: "Cinderella marries the prince, and her days of servitude end for good.",
    },
  },

  // ===== Booker's remaining 3 =====
  {
    id: "lotr-the-quest",
    title: "The Lord of the Rings",
    creator: "J.R.R. Tolkien, 1954–55",
    appliesToType: "plotType",
    appliesToId: "the-quest",
    beats: {
      setup: "Frodo Baggins inherits a Ring of terrible power and learns it must be destroyed to save Middle-earth.",
      rise: "The Fellowship sets out for Mordor, facing Orcs, betrayal, and the loss of their guide Gandalf along the way.",
      climax: "Frodo and Sam reach the edge of Mount Doom, exhausted and consumed by the Ring's corrupting will.",
      fall: "The Ring is destroyed, Sauron's power collapses, and Frodo returns home forever changed by what the journey cost him.",
    },
  },
  {
    id: "midsummer-comedy",
    title: "A Midsummer Night's Dream",
    creator: "William Shakespeare, c. 1595",
    appliesToType: "plotType",
    appliesToId: "comedy",
    beats: {
      setup: "Four young Athenian lovers, mismatched in their affections, flee into an enchanted forest.",
      rise: "A mischievous fairy's love potion causes chaos, making the wrong lovers fall for each other overnight.",
      climax: "The confusion peaks in a tangle of jealousy and accusation among the four, none of them understanding why.",
      fall: "The fairy king sets things right, the correct couples are reunited, and the play ends in a triple wedding.",
    },
  },
  {
    id: "christmas-carol-rebirth",
    title: "A Christmas Carol",
    creator: "Charles Dickens, 1843",
    appliesToType: "plotType",
    appliesToId: "rebirth",
    beats: {
      setup: "Ebenezer Scrooge is a miserly, joyless old man who despises Christmas and everyone who enjoys it.",
      rise: "Three ghosts show him his past, present, and the bleak future his selfishness is leading toward.",
      climax: "Scrooge sees his own unmourned death and the destruction his greed has caused those around him.",
      fall: "Terrified into change, Scrooge wakes transformed — generous, warm, and eager to make amends.",
    },
  },

  // ===== Tobias' 20 Master Plots =====
  {
    id: "lotr-tobias-quest",
    title: "The Lord of the Rings",
    creator: "J.R.R. Tolkien, 1954–55",
    appliesToType: "plotType",
    appliesToId: "tobias-quest",
    beats: {
      setup: "Frodo Baggins inherits a Ring of terrible power that must be destroyed to save Middle-earth.",
      rise: "The Fellowship treks toward Mordor, facing Orcs, betrayal, and the loss of Gandalf along the way.",
      climax: "Frodo and Sam reach the edge of Mount Doom, exhausted and consumed by the Ring's corrupting will.",
      fall: "The Ring is destroyed and Sauron's power collapses, though Frodo returns home forever changed.",
    },
  },
  {
    id: "raiders-tobias-adventure",
    title: "Raiders of the Lost Ark",
    creator: "dir. Steven Spielberg, 1981",
    appliesToType: "plotType",
    appliesToId: "tobias-adventure",
    beats: {
      setup: "Indiana Jones is recruited to find the Ark of the Covenant before the Nazis can use its power.",
      rise: "He travels from Nepal to Cairo, racing rivals and evading danger to trace the Ark's location.",
      climax: "Indy risks everything in a commando raid to steal the Ark back from a moving Nazi convoy.",
      fall: "He survives the Ark's terrible power unleashed on his enemies, delivering it — bruised but victorious — to safety.",
    },
  },
  {
    id: "fugitive-tobias-pursuit",
    title: "The Fugitive",
    creator: "dir. Andrew Davis, 1993",
    appliesToType: "plotType",
    appliesToId: "tobias-pursuit",
    beats: {
      setup: "Dr. Richard Kimble is wrongly convicted of murdering his wife and sentenced to death.",
      rise: "He escapes custody during a prison transport crash and goes on the run, hunted by U.S. Marshal Sam Gerard.",
      climax: "Kimble and Gerard's cat-and-mouse chase converges as Kimble closes in on the real killer.",
      fall: "Kimble proves his innocence and exposes the real killer, with Gerard finally on his side.",
    },
  },
  {
    id: "taken-tobias-rescue",
    title: "Taken",
    creator: "dir. Pierre Morel, 2008",
    appliesToType: "plotType",
    appliesToId: "tobias-rescue",
    beats: {
      setup: "Bryan Mills' daughter Kim is kidnapped by human traffickers while traveling in Paris.",
      rise: "Bryan uses his covert-operative skills to track the kidnappers through Europe's criminal underworld.",
      climax: "He infiltrates the trafficking ring's stronghold in a final, violent confrontation to reach his daughter.",
      fall: "Bryan rescues Kim and brings her home safely, the ordeal reshaping their relationship.",
    },
  },
  {
    id: "shawshank-tobias-escape",
    title: "The Shawshank Redemption",
    creator: "dir. Frank Darabont, 1994",
    appliesToType: "plotType",
    appliesToId: "tobias-escape",
    beats: {
      setup: "Andy Dufresne, a banker wrongly convicted of murder, begins a life sentence at Shawshank Prison.",
      rise: "Over years, he quietly earns trust, launders money for corrupt guards, and tunnels through his cell wall in secret.",
      climax: "Andy makes his escape through the prison's sewage pipe during a single stormy night.",
      fall: "He emerges free, exposes the warden's corruption, and starts a new life on a beach in Mexico.",
    },
  },
  {
    id: "monte-cristo-tobias-revenge",
    title: "The Count of Monte Cristo",
    creator: "Alexandre Dumas, 1844–46",
    appliesToType: "plotType",
    appliesToId: "tobias-revenge",
    beats: {
      setup: "Edmond Dantès is falsely imprisoned by jealous rivals on the eve of his wedding.",
      rise: "After years in prison, he escapes with a fortune and reinvents himself as the mysterious Count of Monte Cristo.",
      climax: "He methodically destroys the men who betrayed him, one by one, using their own weaknesses against them.",
      fall: "Having taken his revenge, Dantès must decide whether it has left him anything worth living for.",
    },
  },
  {
    id: "da-vinci-code-tobias-riddle",
    title: "The Da Vinci Code",
    creator: "Dan Brown, 2003",
    appliesToType: "plotType",
    appliesToId: "tobias-riddle",
    beats: {
      setup: "Symbologist Robert Langdon is drawn into a murder investigation built around a trail of hidden codes.",
      rise: "Langdon and Sophie Neveu follow clues through art, history and secret societies, one step ahead of those hunting them.",
      climax: "The final clues point to a truth that threatens to upend centuries of religious history.",
      fall: "The mystery is solved, revealing a secret Langdon must decide what to do with.",
    },
  },
  {
    id: "amadeus-tobias-rivalry",
    title: "Amadeus",
    creator: "dir. Miloš Forman, 1984",
    appliesToType: "plotType",
    appliesToId: "tobias-rivalry",
    beats: {
      setup: "Composer Antonio Salieri is devoted to God and music, until the brilliant, vulgar young Mozart arrives at court.",
      rise: "Salieri's admiration curdles into obsessive jealousy as Mozart's genius consistently outshines his own hard-won skill.",
      climax: "Salieri schemes to destroy Mozart, secretly commissioning a requiem meant for Mozart's own funeral.",
      fall: "Mozart dies in poverty and obscurity while Salieri lives on, tormented by having engineered it.",
    },
  },
  {
    id: "rocky-tobias-underdog",
    title: "Rocky",
    creator: "dir. John G. Avildsen, 1976",
    appliesToType: "plotType",
    appliesToId: "tobias-underdog",
    beats: {
      setup: "Rocky Balboa is a small-time boxer with no real prospects, scraping by in Philadelphia.",
      rise: "Given a shot at the heavyweight title, he trains relentlessly against impossible odds.",
      climax: "Rocky goes the distance against champion Apollo Creed, a fight no one expected him to survive.",
      fall: "He loses the decision but proves to himself and everyone else that he was never really the underdog he seemed.",
    },
  },
  {
    id: "dorian-gray-tobias-temptation",
    title: "The Picture of Dorian Gray",
    creator: "Oscar Wilde, 1890",
    appliesToType: "plotType",
    appliesToId: "tobias-temptation",
    beats: {
      setup: "Dorian Gray, young and beautiful, wishes his portrait would age instead of him.",
      rise: "Free of consequence, he pursues every pleasure and vice, growing more corrupt while his portrait alone bears the damage.",
      climax: "The portrait grows monstrous, reflecting the full horror of the life Dorian has actually lived.",
      fall: "Dorian destroys the painting in a final act, and his own body instantly bears all the years and sins he'd escaped.",
    },
  },
  {
    id: "metamorphosis-tobias-metamorphosis",
    title: "The Metamorphosis",
    creator: "Franz Kafka, 1915",
    appliesToType: "plotType",
    appliesToId: "tobias-metamorphosis",
    beats: {
      setup: "Gregor Samsa wakes one morning to find himself transformed into a giant insect.",
      rise: "His family, horrified and ashamed, isolates him further as he struggles to adapt to his new form.",
      climax: "Gregor's increasing alienation from his family reaches a breaking point after an incident terrifies them further.",
      fall: "Gregor dies, unmourned by a family relieved to be free of him, who move on without him.",
    },
  },
  {
    id: "beauty-beast-tobias-transformation",
    title: "Beauty and the Beast",
    creator: "traditional / Disney, 1991",
    appliesToType: "plotType",
    appliesToId: "tobias-transformation",
    beats: {
      setup: "Belle is taken prisoner by a cursed Beast in exchange for her father's freedom.",
      rise: "Despite her fear, Belle and the Beast slowly grow to understand and care for each other.",
      climax: "The Beast releases Belle to save her father, risking losing her forever just as he's learned to love.",
      fall: "Belle returns to save him, and her love breaks the curse, transforming him back into a man.",
    },
  },
  {
    id: "mockingbird-tobias-maturation",
    title: "To Kill a Mockingbird",
    creator: "Harper Lee, 1960",
    appliesToType: "plotType",
    appliesToId: "tobias-maturation",
    beats: {
      setup: "Scout Finch grows up in a small Alabama town where her father Atticus defends a Black man falsely accused of rape.",
      rise: "Scout witnesses the town's ugliness and prejudice up close as the trial divides the community.",
      climax: "Despite Atticus's defense, the all-white jury convicts an innocent man, and violence follows.",
      fall: "Scout comes away with a harder, truer understanding of justice, courage, and the adult world's failures.",
    },
  },
  {
    id: "pride-prejudice-tobias-love",
    title: "Pride and Prejudice",
    creator: "Jane Austen, 1813",
    appliesToType: "plotType",
    appliesToId: "tobias-love",
    beats: {
      setup: "Elizabeth Bennet and Mr. Darcy take an instant dislike to each other at a country ball.",
      rise: "Pride, misunderstanding and prejudice on both sides keep pulling them apart even as circumstances draw them together.",
      climax: "Darcy's quiet intervention to save Elizabeth's sister's reputation forces Elizabeth to see him differently.",
      fall: "Both having overcome their own flaws, Elizabeth and Darcy finally admit their feelings and marry.",
    },
  },
  {
    id: "romeo-juliet-tobias-forbidden-love",
    title: "Romeo and Juliet",
    creator: "William Shakespeare, c. 1595",
    appliesToType: "plotType",
    appliesToId: "tobias-forbidden-love",
    beats: {
      setup: "Romeo and Juliet fall in love at first sight, unaware — then all too aware — that their families are sworn enemies.",
      rise: "They marry in secret, but the feud between their families keeps escalating around them.",
      climax: "A fatal duel forces Romeo into exile just as their secret marriage should have offered them a future.",
      fall: "A plan to reunite them collapses into tragedy, and both die rather than live without each other.",
    },
  },
  {
    id: "tale-two-cities-tobias-sacrifice",
    title: "A Tale of Two Cities",
    creator: "Charles Dickens, 1859",
    appliesToType: "plotType",
    appliesToId: "tobias-sacrifice",
    beats: {
      setup: "Sydney Carton, a dissolute lawyer, loves Lucie Manette, who is married to a man who closely resembles him.",
      rise: "Revolutionary France condemns Lucie's husband Darnay to the guillotine, and Carton resolves to act.",
      climax: "Carton switches places with Darnay in prison, sacrificing himself to save the man Lucie loves.",
      fall: "Carton goes to the guillotine in Darnay's place, finding peace in the meaning of his sacrifice.",
    },
  },
  {
    id: "truman-show-tobias-discovery",
    title: "The Truman Show",
    creator: "dir. Peter Weir, 1998",
    appliesToType: "plotType",
    appliesToId: "tobias-discovery",
    beats: {
      setup: "Truman Burbank lives an apparently ordinary life, unaware it's all a constructed television set.",
      rise: "Small inconsistencies — a falling light, a rerun weatherman — begin to make Truman suspect something's wrong.",
      climax: "Truman sails to the edge of his artificial world and finds the literal wall of the dome enclosing it.",
      fall: "He chooses to walk out the studio door into the real world, leaving his entire manufactured life behind.",
    },
  },
  {
    id: "gatsby-tobias-wretched-excess",
    title: "The Great Gatsby",
    creator: "F. Scott Fitzgerald, 1925",
    appliesToType: "plotType",
    appliesToId: "tobias-wretched-excess",
    beats: {
      setup: "Jay Gatsby throws lavish, extravagant parties, all in pursuit of winning back his lost love Daisy.",
      rise: "His obsession with wealth and image grows more consuming as he tries to recreate a past that can't return.",
      climax: "Gatsby's carefully built world collapses when Daisy chooses not to leave her husband for him after all.",
      fall: "Gatsby is killed for a crime that wasn't his, his funeral attended by almost no one from the world he built.",
    },
  },
  {
    id: "pursuit-happyness-tobias-ascension",
    title: "The Pursuit of Happyness",
    creator: "dir. Gabriele Muccino, 2006",
    appliesToType: "plotType",
    appliesToId: "tobias-ascension",
    beats: {
      setup: "Chris Gardner is broke and homeless, struggling to care for his young son while chasing a stockbroker internship.",
      rise: "He works an unpaid internship by day and searches for shelter each night, refusing to give up.",
      climax: "Chris pushes through his hardest, most exhausting stretch, right before the internship's outcome is decided.",
      fall: "He's offered a full-time position, the reward for a climb that nearly broke him.",
    },
  },
  {
    id: "breaking-bad-tobias-descension",
    title: "Breaking Bad",
    creator: "created by Vince Gilligan, 2008–13",
    appliesToType: "plotType",
    appliesToId: "tobias-descension",
    beats: {
      setup: "Walter White, a mild-mannered chemistry teacher, is diagnosed with terminal cancer and starts making methamphetamine to provide for his family.",
      rise: "Success in the drug trade feeds Walter's ego, and he makes increasingly ruthless choices to protect and expand it.",
      climax: "Walter's lies and violence catch up with him, costing him his family, his safety, and nearly everyone he once protected.",
      fall: "He dies alone, having become the very danger he once told himself he was protecting his family from.",
    },
  },

  // ===== Polti's 36 Dramatic Situations =====
  {
    id: "oliver-twist-polti-supplication",
    title: "Oliver Twist",
    creator: "Charles Dickens, 1838",
    appliesToType: "plotType",
    appliesToId: "polti-supplication",
    beats: {
      setup: "Oliver Twist grows up abused and starving in a workhouse, with no one to appeal to.",
      rise: "He famously begs for more food and is punished severely for the request.",
      climax: "Sold into apprenticeship and later drawn into a gang of pickpockets, Oliver has no power to change his circumstances himself.",
      fall: "Kind strangers eventually intervene on his behalf, rescuing him from the life he was powerless to escape alone.",
    },
  },
  {
    id: "exodus-polti-deliverance",
    title: "The Book of Exodus",
    creator: "Hebrew Bible",
    appliesToType: "plotType",
    appliesToId: "polti-deliverance",
    beats: {
      setup: "The Israelites live enslaved in Egypt under Pharaoh's harsh rule.",
      rise: "Moses confronts Pharaoh again and again, demanding freedom for his people.",
      climax: "The ten plagues devastate Egypt until Pharaoh finally, briefly, relents.",
      fall: "Moses leads the Israelites out of Egypt and through the parted sea to freedom.",
    },
  },
  {
    id: "monte-cristo-polti-crime-vengeance",
    title: "The Count of Monte Cristo",
    creator: "Alexandre Dumas, 1844–46",
    appliesToType: "plotType",
    appliesToId: "polti-crime-vengeance",
    beats: {
      setup: "Edmond Dantès is falsely imprisoned by jealous rivals on the eve of his wedding.",
      rise: "After years in prison, he escapes with a fortune and reinvents himself as the mysterious Count of Monte Cristo.",
      climax: "He methodically destroys the men who betrayed him, one by one, using their own weaknesses against them.",
      fall: "Having taken his revenge, Dantès must decide whether it has left him anything worth living for.",
    },
  },
  {
    id: "godfather-polti-vengeance-kindred",
    title: "The Godfather",
    creator: "dir. Francis Ford Coppola, 1972",
    appliesToType: "plotType",
    appliesToId: "polti-vengeance-kindred",
    beats: {
      setup: "The Corleone family is attacked, and Vito Corleone is nearly killed by a rival family's hitmen.",
      rise: "Michael Corleone takes vengeance into his own hands, killing the men responsible.",
      climax: "A war between crime families escalates, with each side's kin becoming targets in turn.",
      fall: "Michael settles every score at once, striking against the heads of the rival families that wronged his own.",
    },
  },
  {
    id: "fugitive-polti-pursuit",
    title: "The Fugitive",
    creator: "dir. Andrew Davis, 1993",
    appliesToType: "plotType",
    appliesToId: "polti-pursuit",
    beats: {
      setup: "Dr. Richard Kimble is wrongly convicted of murdering his wife and sentenced to death.",
      rise: "He escapes custody during a prison transport crash and goes on the run.",
      climax: "U.S. Marshal Sam Gerard closes in on Kimble at every turn, forcing increasingly desperate evasions.",
      fall: "Kimble finally corners the real killer himself, proving his innocence to the marshal who'd hunted him.",
    },
  },
  {
    id: "titanic-polti-disaster",
    title: "Titanic",
    creator: "dir. James Cameron, 1997",
    appliesToType: "plotType",
    appliesToId: "polti-disaster",
    beats: {
      setup: "The 'unsinkable' RMS Titanic sets sail on its maiden voyage, carrying passengers of every class.",
      rise: "The ship strikes an iceberg in the night, and water begins flooding in far faster than anyone expects.",
      climax: "As the ship breaks apart and sinks, passengers scramble for the too-few lifeboats.",
      fall: "Over 1,500 people die in the freezing water, and the survivors are left to carry what they witnessed.",
    },
  },
  {
    id: "job-polti-cruelty-misfortune",
    title: "The Book of Job",
    creator: "Hebrew Bible",
    appliesToType: "plotType",
    appliesToId: "polti-cruelty-misfortune",
    beats: {
      setup: "Job is a righteous, prosperous man with a large family and great wealth.",
      rise: "He loses his children, his wealth, and his health in a rapid, seemingly unearned series of disasters.",
      climax: "Job's friends insist he must have sinned to deserve this, while Job insists on his own innocence.",
      fall: "Job's fortunes are eventually restored, though the suffering itself is never fully explained to him.",
    },
  },
  {
    id: "les-miserables-polti-revolt",
    title: "Les Misérables",
    creator: "Victor Hugo, 1862",
    appliesToType: "plotType",
    appliesToId: "polti-revolt",
    beats: {
      setup: "Jean Valjean, an ex-convict, has rebuilt his life, but Inspector Javert is determined to find and punish him.",
      rise: "Amid growing poverty and injustice in Paris, a group of young revolutionaries plans an uprising.",
      climax: "The students build a barricade and revolt against the government, most of them dying in the failed uprising.",
      fall: "Valjean survives, having saved the wounded revolutionary Marius, and finds peace before his death.",
    },
  },
  {
    id: "apollo-13-polti-daring-enterprise",
    title: "Apollo 13",
    creator: "dir. Ron Howard, 1995",
    appliesToType: "plotType",
    appliesToId: "polti-daring-enterprise",
    beats: {
      setup: "The Apollo 13 crew launches toward the moon on what should be a routine mission.",
      rise: "An oxygen tank explosion cripples the spacecraft, forcing an improvised, high-risk plan just to survive.",
      climax: "The crew and mission control attempt a dangerous engine burn to slingshot them back toward Earth.",
      fall: "Against the odds, all three astronauts make it home safely.",
    },
  },
  {
    id: "taken-polti-abduction",
    title: "Taken",
    creator: "dir. Pierre Morel, 2008",
    appliesToType: "plotType",
    appliesToId: "polti-abduction",
    beats: {
      setup: "Bryan Mills' daughter Kim is kidnapped by human traffickers while traveling in Paris.",
      rise: "Bryan uses his covert-operative skills to track the kidnappers through Europe's criminal underworld.",
      climax: "He infiltrates the trafficking ring's stronghold in a final, violent confrontation to reach his daughter.",
      fall: "Bryan rescues Kim and brings her home safely, the ordeal reshaping their relationship.",
    },
  },
  {
    id: "hound-baskervilles-polti-enigma",
    title: "The Hound of the Baskervilles",
    creator: "Arthur Conan Doyle, 1902",
    appliesToType: "plotType",
    appliesToId: "polti-enigma",
    beats: {
      setup: "Sherlock Holmes is asked to investigate the legend of a supernatural hound linked to a family curse and a suspicious death.",
      rise: "Watson investigates the moor alone, uncovering escaped convicts and suspicious neighbors while a mysterious hound howls in the night.",
      climax: "Holmes reveals himself to have been secretly investigating all along, just as the real hound attacks.",
      fall: "The hound is revealed to be a real dog, disguised to exploit the legend, and the culprit behind it is exposed.",
    },
  },
  {
    id: "raiders-polti-obtaining",
    title: "Raiders of the Lost Ark",
    creator: "dir. Steven Spielberg, 1981",
    appliesToType: "plotType",
    appliesToId: "polti-obtaining",
    beats: {
      setup: "Indiana Jones is recruited to find the Ark of the Covenant before the Nazis do.",
      rise: "He races rivals and Nazi agents across Nepal and Egypt to trace the Ark's hidden location.",
      climax: "He finds it first, only to have Belloq and the Nazis seize it from him at gunpoint.",
      fall: "A daring raid lets Indy reclaim the Ark, delivering it to safety despite everything stacked against him.",
    },
  },
  {
    id: "hamlet-polti-enmity-kinsmen",
    title: "Hamlet",
    creator: "William Shakespeare, c. 1600",
    appliesToType: "plotType",
    appliesToId: "polti-enmity-kinsmen",
    beats: {
      setup: "Prince Hamlet's father, the king, has died, and his uncle Claudius has swiftly married Hamlet's mother and taken the throne.",
      rise: "His father's ghost reveals Claudius murdered him, and Hamlet begins plotting revenge while feigning madness.",
      climax: "Hamlet's staged play provokes Claudius into revealing his guilt, and the plots between them multiply.",
      fall: "Nearly the entire royal family dies in the final confrontation, kinsman against kinsman.",
    },
  },
  {
    id: "king-lear-polti-rivalry-kinsmen",
    title: "King Lear",
    creator: "William Shakespeare, c. 1606",
    appliesToType: "plotType",
    appliesToId: "polti-rivalry-kinsmen",
    beats: {
      setup: "King Lear divides his kingdom among his three daughters based on how well they flatter him.",
      rise: "His two elder daughters, having secured their inheritance, turn on Lear and each other for full control.",
      climax: "Betrayal and rivalry among the sisters spirals into open war and murder within the family.",
      fall: "Nearly the whole family, including Lear and his loyal youngest daughter Cordelia, dies before the kingdom is restored to order.",
    },
  },
  {
    id: "double-indemnity-polti-murderous-adultery",
    title: "Double Indemnity",
    creator: "dir. Billy Wilder, 1944",
    appliesToType: "plotType",
    appliesToId: "polti-murderous-adultery",
    beats: {
      setup: "Insurance salesman Walter Neff is drawn into an affair with Phyllis Dietrichson, an unhappily married woman.",
      rise: "Together they plot to murder her husband and collect on a life insurance policy, faking an accident.",
      climax: "Suspicion from Walter's colleague closes in as the two conspirators begin to turn on each other.",
      fall: "The scheme collapses in mutual betrayal and violence, exposing the murder they thought was perfect.",
    },
  },
  {
    id: "yellow-wallpaper-polti-madness",
    title: "The Yellow Wallpaper",
    creator: "Charlotte Perkins Gilman, 1892",
    appliesToType: "plotType",
    appliesToId: "polti-madness",
    beats: {
      setup: "A woman is confined to a room by her husband for a 'rest cure,' forbidden from working or writing.",
      rise: "Isolated and unstimulated, she becomes fixated on the room's strange yellow wallpaper.",
      climax: "She becomes convinced a woman is trapped behind the wallpaper's pattern, trying to break free.",
      fall: "She descends fully into madness, tearing at the wallpaper convinced she has freed the woman within — who is herself.",
    },
  },
  {
    id: "frankenstein-polti-fatal-imprudence",
    title: "Frankenstein",
    creator: "Mary Shelley, 1818",
    appliesToType: "plotType",
    appliesToId: "polti-fatal-imprudence",
    beats: {
      setup: "Victor Frankenstein becomes obsessed with discovering the secret of creating life.",
      rise: "He builds a creature from dead tissue without ever considering what he'll do once it's alive.",
      climax: "Horrified by what he's made, he abandons it — a careless decision that turns the creature toward vengeance.",
      fall: "Victor's failure to think through the consequences of his experiment costs him everyone he loves.",
    },
  },
  {
    id: "oedipus-polti-involuntary-crimes-love",
    title: "Oedipus Rex",
    creator: "Sophocles, c. 429 BCE",
    appliesToType: "plotType",
    appliesToId: "polti-involuntary-crimes-love",
    beats: {
      setup: "Oedipus, raised far from his birth parents, is unaware of a prophecy that he will kill his father and marry his mother.",
      rise: "Fleeing what he believes is his fate, Oedipus unknowingly kills a stranger on the road and later marries the widowed queen.",
      climax: "A plague on the city drives Oedipus to investigate its cause, uncovering the truth of what he's done.",
      fall: "Oedipus realizes the stranger was his father and the queen his mother — the love that undid him was never a knowing crime.",
    },
  },
  {
    id: "oedipus-polti-slaying-kinsman",
    title: "Oedipus Rex",
    creator: "Sophocles, c. 429 BCE",
    appliesToType: "plotType",
    appliesToId: "polti-slaying-kinsman-unrecognized",
    beats: {
      setup: "Oedipus leaves the only parents he's ever known to escape a prophecy that he'll kill his father.",
      rise: "On the road, a confrontation with an arrogant stranger turns violent, and Oedipus kills him without knowing who he is.",
      climax: "Years later, investigating a plague on his city, Oedipus is forced to trace the identity of the man he killed.",
      fall: "The stranger is revealed to have been his true father, King Laius — the kinsman Oedipus slew without recognizing him.",
    },
  },
  {
    id: "tale-two-cities-polti-self-sacrifice-ideal",
    title: "A Tale of Two Cities",
    creator: "Charles Dickens, 1859",
    appliesToType: "plotType",
    appliesToId: "polti-self-sacrifice-ideal",
    beats: {
      setup: "Sydney Carton, a dissolute lawyer, believes his life has amounted to little of value.",
      rise: "He comes to see Lucie Manette's happiness, and the ideal of love itself, as worth more than his own survival.",
      climax: "When her husband Darnay is condemned to the guillotine, Carton resolves to take his place.",
      fall: "Carton dies for the ideal he's chosen, finding meaning in the sacrifice his own life never gave him.",
    },
  },
  {
    id: "harry-potter-polti-self-sacrifice-kindred",
    title: "Harry Potter and the Sorcerer's Stone",
    creator: "J.K. Rowling, 1997",
    appliesToType: "plotType",
    appliesToId: "polti-self-sacrifice-kindred",
    beats: {
      setup: "Lily Potter stands between her infant son Harry and Voldemort, refusing to step aside.",
      rise: "Her death, given freely for her son, leaves a magical protection woven into Harry himself.",
      climax: "Years later, that same protection burns Voldemort's servant when he tries to harm Harry directly.",
      fall: "Harry survives because of a sacrifice he doesn't even remember, carried by a love more powerful than any spell.",
    },
  },
  {
    id: "wuthering-heights-polti-all-sacrificed-passion",
    title: "Wuthering Heights",
    creator: "Emily Brontë, 1847",
    appliesToType: "plotType",
    appliesToId: "polti-all-sacrificed-passion",
    beats: {
      setup: "Heathcliff and Catherine share an intense, consuming bond from childhood, deeper than either can control.",
      rise: "Catherine marries another man for status, and Heathcliff's love curdles into obsession and cruelty.",
      climax: "Heathcliff spends years destroying the lives of everyone connected to Catherine, unable to let go of his passion.",
      fall: "He dies still consumed by her memory, having sacrificed every relationship and any peace for a love that outlasted her.",
    },
  },
  {
    id: "sophies-choice-polti-necessity-sacrificing",
    title: "Sophie's Choice",
    creator: "William Styron, 1979",
    appliesToType: "plotType",
    appliesToId: "polti-necessity-sacrificing-loved-ones",
    beats: {
      setup: "Sophie, a concentration camp prisoner, arrives with her two children under a Nazi officer's control.",
      rise: "The officer forces her into an impossible situation with no acceptable outcome.",
      climax: "Sophie is forced to choose which of her two children will be sent to the gas chamber, and which will live.",
      fall: "She survives the war physically, but the choice she was forced to make haunts and ultimately destroys her.",
    },
  },
  {
    id: "rocky-polti-rivalry-superior-inferior",
    title: "Rocky",
    creator: "dir. John G. Avildsen, 1976",
    appliesToType: "plotType",
    appliesToId: "polti-rivalry-superior-inferior",
    beats: {
      setup: "Rocky Balboa is a small-time club boxer given a shot at the reigning heavyweight champion, Apollo Creed.",
      rise: "Vastly outmatched on paper, Rocky trains obsessively to have any chance at all.",
      climax: "The two finally meet in the ring, Rocky's grit tested against Creed's superior skill.",
      fall: "Rocky loses the decision but goes the distance — the assumed hierarchy between them shaken, if not overturned.",
    },
  },
  {
    id: "anna-karenina-polti-adultery",
    title: "Anna Karenina",
    creator: "Leo Tolstoy, 1877",
    appliesToType: "plotType",
    appliesToId: "polti-adultery",
    beats: {
      setup: "Anna Karenina, married to a respectable but cold official, meets the dashing Count Vronsky.",
      rise: "Their affair becomes public, and Russian high society turns against Anna while Vronsky faces far less consequence.",
      climax: "Isolated, scandalized, and increasingly paranoid about losing Vronsky's love, Anna's situation grows desperate.",
      fall: "Unable to see a way out of her isolation, Anna takes her own life.",
    },
  },
  {
    id: "carmen-polti-crimes-of-love",
    title: "Carmen",
    creator: "Georges Bizet (opera), 1875",
    appliesToType: "plotType",
    appliesToId: "polti-crimes-of-love",
    beats: {
      setup: "Don José, a soldier, becomes infatuated with the free-spirited Carmen and abandons his post for her.",
      rise: "His obsession leads him to desert the army and turn to smuggling to stay near her.",
      climax: "Carmen loses interest in José and turns her attention to a bullfighter, provoking José's jealous rage.",
      fall: "José kills Carmen rather than let her go, a crime born entirely from a love he couldn't control.",
    },
  },
  {
    id: "othello-polti-discovery-dishonor",
    title: "Othello",
    creator: "William Shakespeare, c. 1603",
    appliesToType: "plotType",
    appliesToId: "polti-discovery-dishonor-loved-one",
    beats: {
      setup: "Othello, a respected general, marries Desdemona, whom he loves deeply and trusts completely.",
      rise: "His ensign Iago plants seeds of doubt, fabricating evidence that Desdemona has been unfaithful.",
      climax: "Othello becomes convinced of Desdemona's betrayal, his trust in her collapsing entirely.",
      fall: "Othello kills Desdemona, only to learn moments later that Iago's evidence was a complete fabrication.",
    },
  },
  {
    id: "romeo-juliet-polti-obstacles-love",
    title: "Romeo and Juliet",
    creator: "William Shakespeare, c. 1595",
    appliesToType: "plotType",
    appliesToId: "polti-obstacles-love",
    beats: {
      setup: "Romeo and Juliet fall in love, only to learn their families are bitter, sworn enemies.",
      rise: "They marry in secret, but the feud keeps finding new ways to force them apart.",
      climax: "Romeo's exile after a fatal duel puts the final, seemingly insurmountable obstacle between them.",
      fall: "A plan to reunite them fails to reach Romeo in time, and the obstacle proves fatal to them both.",
    },
  },
  {
    id: "romeo-juliet-polti-enemy-loved",
    title: "Romeo and Juliet",
    creator: "William Shakespeare, c. 1595",
    appliesToType: "plotType",
    appliesToId: "polti-enemy-loved",
    beats: {
      setup: "Juliet discovers at the ball that the boy she's fallen for, Romeo, is a Montague — her family's sworn enemy.",
      rise: "She chooses him anyway, secretly marrying him despite everything her family stands against.",
      climax: "Romeo's killing of her cousin Tybalt forces Juliet to choose openly between her family's hatred and her love.",
      fall: "She stays loyal to Romeo to the end, her love for the 'enemy' outlasting even her own life.",
    },
  },
  {
    id: "macbeth-polti-ambition",
    title: "Macbeth",
    creator: "William Shakespeare, c. 1606",
    appliesToType: "plotType",
    appliesToId: "polti-ambition",
    beats: {
      setup: "Macbeth, a loyal general, is told by three witches that he is destined to become king.",
      rise: "Ambition, fed by his wife, pushes him to murder King Duncan and seize the throne.",
      climax: "He murders more and more to protect his stolen crown, his ambition consuming everyone around him.",
      fall: "His ambition finally collapses under rebellion, and he is killed by the men he wronged to get there.",
    },
  },
  {
    id: "prometheus-polti-conflict-with-god",
    title: "Prometheus (Greek myth)",
    creator: "traditional myth",
    appliesToType: "plotType",
    appliesToId: "polti-conflict-with-god",
    beats: {
      setup: "Prometheus, a Titan, sees humanity struggling in cold darkness without fire.",
      rise: "Defying Zeus's explicit will, he steals fire from the gods and gives it to humankind.",
      climax: "Zeus punishes Prometheus by chaining him to a rock, where an eagle eats his regenerating liver each day.",
      fall: "Prometheus endures his eternal punishment, humanity's gift of fire an irreversible act of defiance against the gods.",
    },
  },
  {
    id: "othello-polti-mistaken-jealousy",
    title: "Othello",
    creator: "William Shakespeare, c. 1603",
    appliesToType: "plotType",
    appliesToId: "polti-mistaken-jealousy",
    beats: {
      setup: "Othello trusts his wife Desdemona completely as their marriage begins.",
      rise: "Iago manufactures false evidence — a misplaced handkerchief — to convince Othello of an affair that never happened.",
      climax: "Othello's jealousy, entirely built on lies, drives him to violence against the wife he loves.",
      fall: "Only after killing Desdemona does Othello learn the truth, and take his own life in grief and horror.",
    },
  },
  {
    id: "crucible-polti-erroneous-judgment",
    title: "The Crucible",
    creator: "Arthur Miller, 1953",
    appliesToType: "plotType",
    appliesToId: "polti-erroneous-judgment",
    beats: {
      setup: "A group of girls in Salem, caught dancing in the woods, accuse others of witchcraft to protect themselves.",
      rise: "The town's courts, eager to believe the accusations, condemn more and more innocent people based on false testimony.",
      climax: "John Proctor, trying to expose the girls' lies, is himself accused and arrested.",
      fall: "Proctor is executed rather than falsely confess, a victim of a judgment built entirely on deception.",
    },
  },
  {
    id: "crime-punishment-polti-remorse",
    title: "Crime and Punishment",
    creator: "Fyodor Dostoevsky, 1866",
    appliesToType: "plotType",
    appliesToId: "polti-remorse",
    beats: {
      setup: "Raskolnikov, a poor former student, murders a pawnbroker, convincing himself he's above ordinary morality.",
      rise: "Guilt and paranoia consume him even as the police fail to connect him to the crime.",
      climax: "His remorse grows unbearable, driving him toward confession despite having nearly gotten away with it.",
      fall: "Raskolnikov confesses and accepts his punishment, finding a path toward redemption through suffering.",
    },
  },
  {
    id: "odyssey-polti-recovery-lost-one",
    title: "The Odyssey",
    creator: "Homer, c. 8th century BCE",
    appliesToType: "plotType",
    appliesToId: "polti-recovery-lost-one",
    beats: {
      setup: "Odysseus has been gone from home for twenty years, presumed dead by most who knew him.",
      rise: "His wife Penelope fends off suitors while his son Telemachus searches for news of his father.",
      climax: "Odysseus finally reaches Ithaca in disguise, testing who around him has stayed loyal.",
      fall: "He reveals himself to Penelope and Telemachus, reunited with the family he never stopped trying to reach.",
    },
  },
  {
    id: "bambi-polti-loss-loved-ones",
    title: "Bambi",
    creator: "Disney, dir. David Hand, 1942",
    appliesToType: "plotType",
    appliesToId: "polti-loss-loved-ones",
    beats: {
      setup: "Bambi, a young deer, grows up under his mother's protection in the forest.",
      rise: "Hunters begin appearing in the forest, and the animals live under constant threat.",
      climax: "Bambi's mother is killed by a hunter while fleeing with him across a meadow.",
      fall: "Bambi grows up without her, eventually becoming a father himself, carrying her loss into his own life.",
    },
  },

  // ===== Vonnegut's Story Shapes =====
  {
    id: "wizard-of-oz-vonnegut-man-in-hole",
    title: "The Wizard of Oz",
    creator: "dir. Victor Fleming, 1939",
    appliesToType: "plotType",
    appliesToId: "vonnegut-man-in-hole",
    beats: {
      setup: "Dorothy lives an ordinary life on a Kansas farm.",
      rise: "A tornado sweeps her into the strange, dangerous land of Oz, far from home and everyone she knows.",
      climax: "She and her friends face the Wicked Witch at her most dangerous, deep into unfamiliar territory.",
      fall: "Dorothy defeats the witch, gets her wish granted, and returns home valuing it more than she ever did before.",
    },
  },
  {
    id: "when-harry-met-sally-vonnegut-boy-meets-girl",
    title: "When Harry Met Sally...",
    creator: "dir. Rob Reiner, 1989",
    appliesToType: "plotType",
    appliesToId: "vonnegut-boy-meets-girl",
    beats: {
      setup: "Harry and Sally meet and instantly clash over whether men and women can ever just be friends.",
      rise: "Over years of crossing paths, their friendship deepens even as romantic complications keep them apart.",
      climax: "A moment of vulnerability threatens to end their friendship entirely just as feelings become undeniable.",
      fall: "They finally admit they're in love and end up together, closer than they'd have been without the wait.",
    },
  },
  {
    id: "cinderella-vonnegut-cinderella",
    title: "Cinderella",
    creator: "traditional folk tale",
    appliesToType: "plotType",
    appliesToId: "vonnegut-cinderella",
    beats: {
      setup: "Cinderella is overworked and mistreated by her stepmother and stepsisters, denied any life of her own.",
      rise: "With her fairy godmother's help, she attends the royal ball and catches the Prince's attention — then flees at midnight, losing a glass slipper.",
      climax: "The Prince's search for the slipper's owner puts Cinderella's fate in the hands of a single, decisive test.",
      fall: "The slipper fits; Cinderella marries the Prince, her worth finally recognized beyond her circumstances.",
    },
  },
  {
    id: "of-mice-and-men-vonnegut-bad-to-worse",
    title: "Of Mice and Men",
    creator: "John Steinbeck, 1937",
    appliesToType: "plotType",
    appliesToId: "vonnegut-bad-to-worse",
    beats: {
      setup: "George and Lennie, migrant workers, dream of one day owning a small farm of their own.",
      rise: "Lennie's immense strength and limited understanding keep causing accidental trouble wherever they go.",
      climax: "Lennie accidentally kills a woman, and a mob forms to hunt him down.",
      fall: "George is forced to kill Lennie himself to spare him a worse death, and the dream of the farm dies with him.",
    },
  },
  {
    id: "hamlet-vonnegut-which-way-up",
    title: "Hamlet",
    creator: "William Shakespeare, c. 1600",
    appliesToType: "plotType",
    appliesToId: "vonnegut-which-way-up",
    beats: {
      setup: "Hamlet is charged with avenging his father's murder, a task that seems clearly righteous.",
      rise: "His delays, feigned madness, and moral hesitation make it unclear whether his path is heroic or self-destructive.",
      climax: "By the final act, nearly everyone around him is dead or doomed, the 'rightness' of his cause deeply muddied.",
      fall: "Hamlet dies having gotten his revenge, but whether the ending is a triumph or a tragedy is left genuinely ambiguous.",
    },
  },
  {
    id: "genesis-vonnegut-creation-story",
    title: "The Book of Genesis",
    creator: "Hebrew Bible",
    appliesToType: "plotType",
    appliesToId: "vonnegut-creation-story",
    beats: {
      setup: "In the beginning, there is nothing — formless void and darkness.",
      rise: "Over six days, light, land, sea, plants, stars, and animals are brought into being in sequence.",
      climax: "Humanity is created last, formed in the divine image, and placed in the Garden of Eden.",
      fall: "Creation is complete and declared very good, the ascent from nothing to everything finished in a single arc.",
    },
  },

  // ===== The MICE Quotient =====
  {
    id: "wizard-of-oz-mice-milieu",
    title: "The Wizard of Oz",
    creator: "dir. Victor Fleming, 1939",
    appliesToType: "plotType",
    appliesToId: "mice-milieu",
    beats: {
      setup: "The story opens as Dorothy is swept from Kansas into the wholly unfamiliar land of Oz.",
      rise: "She travels the yellow brick road, encountering the strange rules and dangers of this new world.",
      climax: "Oz itself reaches its turning point as the Wicked Witch is defeated and the Wizard exposed as a fraud.",
      fall: "The story closes as Dorothy leaves Oz behind and returns to Kansas.",
    },
  },
  {
    id: "da-vinci-code-mice-idea",
    title: "The Da Vinci Code",
    creator: "Dan Brown, 2003",
    appliesToType: "plotType",
    appliesToId: "mice-idea",
    beats: {
      setup: "The story opens on a murder that poses a single burning question: what secret was the victim protecting?",
      rise: "Langdon and Sophie chase clue after clue, each answer opening a deeper question.",
      climax: "The final clue is within reach, at the point of greatest uncertainty about what it will reveal.",
      fall: "The question is answered, and the story ends there, its central mystery resolved.",
    },
  },
  {
    id: "christmas-carol-mice-character",
    title: "A Christmas Carol",
    creator: "Charles Dickens, 1843",
    appliesToType: "plotType",
    appliesToId: "mice-character",
    beats: {
      setup: "The story opens on Scrooge, thoroughly satisfied with the miser he's become.",
      rise: "The ghosts force him to try on other ways of seeing himself, against his fierce resistance.",
      climax: "Confronted with his own unmourned death, Scrooge must decide, urgently, who he's going to be.",
      fall: "The story ends once his transformation is complete and settled, a changed man for good.",
    },
  },
  {
    id: "titanic-mice-event",
    title: "Titanic",
    creator: "dir. James Cameron, 1997",
    appliesToType: "plotType",
    appliesToId: "mice-event",
    beats: {
      setup: "The story opens with the ship's grand order — first class and steerage alike — about to be disrupted.",
      rise: "The collision spreads chaos through the ship, worsening deck by deck as it sinks.",
      climax: "The turning point comes as the ship breaks apart, order fully collapsed into a fight for survival.",
      fall: "The story ends once a new order holds — the rescue, the survivors, the world reckoning with what happened.",
    },
  },
];

export const examplesFor = (type, id) => EXAMPLES.filter(e => e.appliesToType === type && e.appliesToId === id);
export const exampleById = id => EXAMPLES.find(e => e.id === id) || null;
