// Story-structure templates. Each beat carries `pct` (its share of the wheel / the story's total
// length), `act` (a coarse phase used only for colour — Setup / Confrontation / Resolution, or a
// template's own equivalent) so differently-shaped structures still read as one system, `ex`
// (a three-word illustration of the beat, all templates tracing the same example story so they
// read as one throughline — except Kishotenketsu, whose non-conflict shape gets its own), and
// `threeAct` (1/2/3 — where the beat falls against the classic three-act spine, drawn as the
// wheel's outer ring; beats within a structure are listed in non-decreasing threeAct order).

export const ACTS = {
  setup:  { label: "Setup",         color: "#5FA8A0" },
  rise:   { label: "Rising Action", color: "#E9C88A" },
  climax: { label: "Confrontation", color: "#D2785A" },
  fall:   { label: "Resolution",    color: "#8E7CC3" },
};

export const STRUCTURES = [
  {
    id: "three-act",
    name: "Three-Act Structure",
    blurb: "The workhorse: setup, confrontation, resolution. Good default for almost any story.",
    beats: [
      { id: "status-quo",   name: "Opening Image",     pct: 5,  act: "setup",  threeAct: 1, guide: "The world before the story disturbs it. What's the ordinary, in one image or scene?", ex: "Quiet village morning" },
      { id: "inciting",     name: "Inciting Incident",  pct: 7,  act: "setup",  threeAct: 1, guide: "The event that makes the story start. What breaks the ordinary world open?", ex: "Dragon attacks village" },
      { id: "plot-point-1", name: "Reaction to Incident", pct: 8,  act: "setup",  threeAct: 1, guide: "The point of no return — the protagonist commits to the journey.", ex: "Hero grabs sword" },
      { id: "rising",       name: "Getting Friends",    pct: 20, act: "rise",   threeAct: 2, guide: "Obstacles escalate, stakes climb, the protagonist learns the rules of the new world.", ex: "Gathers allies, trains" },
      { id: "midpoint",     name: "Extent of the Evil", pct: 8,  act: "rise",   threeAct: 2, guide: "A false victory or false defeat that shifts the story's direction and raises the stakes.", ex: "Discovers evil's scale" },
      { id: "plot-point-2", name: "Almost Failure",     pct: 12, act: "climax", threeAct: 2, guide: "Everything falls apart. The lowest point, right before the final push.", ex: "Ally betrays hero" },
      { id: "climax",       name: "Final Fight",        pct: 15, act: "climax", threeAct: 3, guide: "The final confrontation. The protagonist's central struggle is decided here.", ex: "Duels dragon alone" },
      { id: "resolution",   name: "Resolution",         pct: 25, act: "fall",   threeAct: 3, guide: "The new normal. Loose threads tie off and the story's change is shown, not told.", ex: "Village rebuilds, thrives" },
    ],
  },
  {
    id: "save-the-cat",
    name: "Save the Cat! (15 beats)",
    blurb: "Blake Snyder's screenwriting beat sheet — precise, percentage-mapped, plot-heavy.",
    beats: [
      { id: "opening-image",   name: "Opening Image",       pct: 1,  act: "setup",  threeAct: 1, guide: "A snapshot of the 'before' — tone, mood, the problem the protagonist doesn't see yet.", ex: "Quiet village morning" },
      { id: "theme-stated",    name: "Theme Stated",        pct: 4,  act: "setup",  threeAct: 1, guide: "Someone (usually not the hero) says the story's real argument out loud, in passing.", ex: "Courage over fear" },
      { id: "set-up",          name: "Set-Up",              pct: 5,  act: "setup",  threeAct: 1, guide: "Introduce the hero's flaws, world, and stakes — everything the story is about to upend.", ex: "Farmer fears dragons" },
      { id: "catalyst",        name: "Catalyst",            pct: 1,  act: "setup",  threeAct: 1, guide: "The telegram, the firing, the knock at the door — the moment life changes.", ex: "Dragon burns barn" },
      { id: "debate",          name: "Debate",              pct: 9,  act: "setup",  threeAct: 1, guide: "Should the hero go? The last chance to say no before the story truly begins.", ex: "Should I go?" },
      { id: "break-into-two",  name: "Break Into Two",      pct: 2,  act: "rise",   threeAct: 2, guide: "The hero chooses (or is forced) to leave the old world and enter the new one.", ex: "Leaves the farm" },
      { id: "b-story",         name: "B Story",             pct: 4,  act: "rise",   threeAct: 2, guide: "A new relationship enters, usually carrying the story's theme.", ex: "Meets fellow warrior" },
      { id: "fun-and-games",   name: "Fun and Games",       pct: 19, act: "rise",   threeAct: 2, guide: "The 'promise of the premise' — the trailer moments, playing in the new world.", ex: "Trains, tracks, jokes" },
      { id: "midpoint",        name: "Midpoint",            pct: 1,  act: "rise",   threeAct: 2, guide: "A false victory or false defeat. Stakes rise from personal to life-and-death.", ex: "Finds dragon's lair" },
      { id: "bad-guys-close",  name: "Bad Guys Close In",   pct: 11, act: "climax", threeAct: 2, guide: "Internal doubts and external pressure both close in on the hero.", ex: "Elders lose hope" },
      { id: "all-is-lost",     name: "All Is Lost",         pct: 1,  act: "climax", threeAct: 2, guide: "The opposite of the midpoint's win — often a 'whiff of death', literal or symbolic.", ex: "Warrior friend dies" },
      { id: "dark-night",      name: "Dark Night of the Soul", pct: 4, act: "climax", threeAct: 2, guide: "The hero sits in the wreckage before finding the way forward.", ex: "Grieves, nearly quits" },
      { id: "break-into-three",name: "Break Into Three",    pct: 2,  act: "fall",   threeAct: 3, guide: "The A and B stories combine to hand the hero the solution.", ex: "Remembers warrior's lesson" },
      { id: "finale",          name: "Finale",              pct: 15, act: "fall",   threeAct: 3, guide: "The hero applies what they learned to defeat the antagonist and fix the world.", ex: "Defeats the dragon" },
      { id: "final-image",     name: "Final Image",         pct: 1,  act: "fall",   threeAct: 3, guide: "A mirror of the opening image, showing exactly how much has changed.", ex: "Village rebuilds, thrives" },
    ],
  },
  {
    id: "hero-journey",
    name: "The Hero's Journey",
    blurb: "Campbell / Vogler's 12-stage monomyth — myth, fantasy and quest stories.",
    beats: [
      { id: "ordinary-world",  name: "Ordinary World",         pct: 8,  act: "setup",  threeAct: 1, guide: "The hero's normal life, and what's missing or unresolved in it.", ex: "Quiet village morning" },
      { id: "call",            name: "Call to Adventure",      pct: 6,  act: "setup",  threeAct: 1, guide: "A problem or challenge is presented — the story's invitation.", ex: "Dragon attacks village" },
      { id: "refusal",         name: "Refusal of the Call",    pct: 5,  act: "setup",  threeAct: 1, guide: "Fear or doubt makes the hero hesitate, reluctant to change.", ex: "Hero refuses, afraid" },
      { id: "mentor",          name: "Meeting the Mentor",     pct: 6,  act: "setup",  threeAct: 1, guide: "A guide offers wisdom, training, or an item that prepares the hero.", ex: "Old warrior teaches" },
      { id: "threshold",       name: "Crossing the Threshold", pct: 5,  act: "rise",   threeAct: 1, guide: "The hero commits and leaves the ordinary world behind for good.", ex: "Leaves the village" },
      { id: "tests-allies",    name: "Tests, Allies, Enemies", pct: 14, act: "rise",   threeAct: 2, guide: "The new world is explored — friends, rivals and the rules are learned the hard way.", ex: "Makes allies, enemies" },
      { id: "approach",        name: "Approach to the Inmost Cave", pct: 8, act: "rise", threeAct: 2, guide: "Preparation for the central ordeal; the plan is made and the stakes sharpen.", ex: "Plans the assault" },
      { id: "ordeal",          name: "Ordeal",                 pct: 10, act: "climax", threeAct: 2, guide: "The hero's greatest fear or crisis — a life-or-death, all-or-nothing moment.", ex: "Faces the dragon" },
      { id: "reward",          name: "Reward",                 pct: 8,  act: "climax", threeAct: 2, guide: "Having survived, the hero seizes what they came for — but it comes at a cost.", ex: "Claims dragon's treasure" },
      { id: "road-back",       name: "The Road Back",          pct: 8,  act: "climax", threeAct: 2, guide: "The hero commits to finishing the journey; the consequences of the ordeal chase them.", ex: "Danger follows home" },
      { id: "resurrection",    name: "Resurrection",           pct: 12, act: "fall",   threeAct: 3, guide: "A final, larger test where everything learned is proven — a true climax.", ex: "Final desperate stand" },
      { id: "elixir",          name: "Return with the Elixir", pct: 10, act: "fall",   threeAct: 3, guide: "The hero returns changed, bringing something of value back to the ordinary world.", ex: "Brings peace home" },
    ],
  },
  {
    id: "freytag",
    name: "Freytag's Pyramid",
    blurb: "The classic five-part dramatic arc — simple, stage-friendly, tragedy's native shape.",
    beats: [
      { id: "exposition",     name: "Exposition",     pct: 15, act: "setup",  threeAct: 1, guide: "Establish characters, setting and the world's status quo.", ex: "Quiet village morning" },
      { id: "rising-action",  name: "Rising Action",  pct: 30, act: "rise",   threeAct: 2, guide: "A series of complicating events builds tension toward the climax.", ex: "Dragon threat grows" },
      { id: "climax",         name: "Climax",         pct: 15, act: "climax", threeAct: 2, guide: "The turning point — the moment of highest tension, where fortune reverses.", ex: "Hero fights dragon" },
      { id: "falling-action", name: "Falling Action", pct: 25, act: "climax", threeAct: 3, guide: "Consequences of the climax play out; tension unwinds toward the ending.", ex: "Dragon's power fades" },
      { id: "denouement",     name: "Denouement",     pct: 15, act: "fall",   threeAct: 3, guide: "Loose ends resolve and the story's new equilibrium is shown.", ex: "Peace returns finally" },
    ],
  },
  {
    id: "seven-point",
    name: "Seven-Point Story Structure",
    blurb: "Dan Wells' structure, built backward from the ending — good for tight plotting.",
    beats: [
      { id: "hook",       name: "Hook",         pct: 8,  act: "setup",  threeAct: 1, guide: "The opposite of the resolution — establish where the character starts, in contrast to where they'll end.", ex: "Hero fears dragons" },
      { id: "plot-turn-1",name: "Plot Turn 1",  pct: 12, act: "setup",  threeAct: 1, guide: "An event introduces the main conflict and moves the character out of the hook state.", ex: "Dragon attacks village" },
      { id: "pinch-1",    name: "Pinch Point 1",pct: 15, act: "rise",   threeAct: 2, guide: "Pressure is applied — often the antagonist's power is shown, forcing the character to act.", ex: "Dragon burns fields" },
      { id: "midpoint",   name: "Midpoint",     pct: 12, act: "rise",   threeAct: 2, guide: "The character moves from reaction to action — passive to proactive.", ex: "Hero chooses action" },
      { id: "pinch-2",    name: "Pinch Point 2",pct: 15, act: "climax", threeAct: 2, guide: "More pressure, often a major loss, that removes the character's safety net entirely.", ex: "Mentor is killed" },
      { id: "plot-turn-2",name: "Plot Turn 2",  pct: 13, act: "climax", threeAct: 3, guide: "The final piece the character needs to resolve the conflict is found.", ex: "Finds dragon's weakness" },
      { id: "resolution", name: "Resolution",   pct: 25, act: "fall",   threeAct: 3, guide: "The character, now changed, resolves the conflict — the mirror of the hook.", ex: "Hero defeats dragon" },
    ],
  },
  {
    id: "kishotenketsu",
    name: "Kishōtenketsu",
    blurb: "A four-act East Asian narrative structure driven by contrast, not conflict.",
    beats: [
      { id: "ki",     name: "Ki (Introduction)", pct: 25, act: "setup",  threeAct: 1, guide: "Introduce the characters and situation, unhurried — no problem needs to appear yet.", ex: "Village bakes bread" },
      { id: "sho",    name: "Shō (Development)", pct: 30, act: "rise",   threeAct: 2, guide: "Develop what was introduced; deepen the reader's understanding of the situation.", ex: "Baker befriends traveler" },
      { id: "ten",    name: "Ten (Twist)",       pct: 25, act: "climax", threeAct: 3, guide: "An unexpected, often unrelated element recontextualises everything that came before.", ex: "Traveler is dragon" },
      { id: "ketsu",  name: "Ketsu (Conclusion)",pct: 20, act: "fall",   threeAct: 3, guide: "Reconcile the twist with the rest of the story into a single, resolved whole.", ex: "Village welcomes dragon" },
    ],
  },
  {
    id: "fichtean",
    name: "Fichtean Curve",
    blurb: "No slow build — opens already in conflict, then a rising series of crises to the climax.",
    beats: [
      { id: "crisis-1", name: "Opening Crisis",   pct: 10, act: "setup",  threeAct: 1, guide: "Skip the calm-before — open already inside a conflict; the 'before' comes out sideways, later, if at all.", ex: "Dragon burns village" },
      { id: "crisis-2", name: "Crisis Two",       pct: 15, act: "rise",   threeAct: 1, guide: "A second crisis, arriving fast, reveals the shape of the larger problem.", ex: "Second attack strikes" },
      { id: "crisis-3", name: "Crisis Three",     pct: 18, act: "rise",   threeAct: 2, guide: "Each crisis raises the stakes higher than the last — no plateau, no breathing room.", ex: "Allies start dying" },
      { id: "crisis-4", name: "Crisis Four",      pct: 20, act: "climax", threeAct: 2, guide: "The pressure peaks just short of the climax — the worst point before the final crisis.", ex: "Village nearly falls" },
      { id: "climax",   name: "Climax",           pct: 20, act: "climax", threeAct: 3, guide: "The largest crisis of all, where the central conflict is finally decided.", ex: "Hero faces dragon" },
      { id: "resolution", name: "Resolution",     pct: 17, act: "fall",   threeAct: 3, guide: "A brief denouement — the Fichtean curve spends almost no time here.", ex: "Peace, briefly restored" },
    ],
  },
  {
    id: "story-circle",
    name: "Dan Harmon's Story Circle",
    blurb: "Campbell's monomyth compressed to 8 equal steps, built explicitly as a circle.",
    beats: [
      { id: "you",    name: "You",    pct: 12, act: "setup",  threeAct: 1, guide: "A character in their zone of comfort.", ex: "Farmer tends fields" },
      { id: "need",   name: "Need",   pct: 13, act: "setup",  threeAct: 1, guide: "They want something.", ex: "Wants safety, purpose" },
      { id: "go",     name: "Go",     pct: 13, act: "rise",   threeAct: 1, guide: "They enter an unfamiliar situation.", ex: "Leaves the farm" },
      { id: "search", name: "Search", pct: 12, act: "rise",   threeAct: 2, guide: "They adapt to it.", ex: "Learns to fight" },
      { id: "find",   name: "Find",   pct: 12, act: "rise",   threeAct: 2, guide: "They get what they wanted.", ex: "Finds dragon's lair" },
      { id: "take",   name: "Take",   pct: 12, act: "climax", threeAct: 2, guide: "They pay a heavy price for it.", ex: "Loses a friend" },
      { id: "return", name: "Return", pct: 13, act: "climax", threeAct: 3, guide: "They return to the familiar situation.", ex: "Returns to village" },
      { id: "change", name: "Change", pct: 13, act: "fall",   threeAct: 3, guide: "Now capable of change, having changed.", ex: "Villagers see change" },
    ],
  },
  {
    id: "eight-sequence",
    name: "Eight-Sequence Structure",
    blurb: "Frank Daniel's film-school standard: eight roughly equal mini-movies, each with its own turn.",
    beats: [
      { id: "status-quo", name: "Status Quo & Inciting Incident", pct: 12, act: "setup",  threeAct: 1, guide: "Establish the world, then break it.", ex: "Dragon attacks village" },
      { id: "predicament",name: "Predicament",                    pct: 12, act: "setup",  threeAct: 1, guide: "Lock the protagonist into a goal they can't walk away from.", ex: "Vows to fight" },
      { id: "obstacle-1", name: "First Obstacle",                 pct: 13, act: "rise",   threeAct: 1, guide: "The first real attempt runs into trouble.", ex: "First attack fails" },
      { id: "stakes-1",   name: "Raising the Stakes",              pct: 13, act: "rise",   threeAct: 2, guide: "Complications mount on the way to the midpoint.", ex: "Village losses mount" },
      { id: "midpoint",   name: "Midpoint Reversal",               pct: 12, act: "rise",   threeAct: 2, guide: "A turn that changes the direction of the plan.", ex: "Learns dragon's weakness" },
      { id: "stakes-2",   name: "Raising the Stakes Further",      pct: 13, act: "climax", threeAct: 2, guide: "Pressure builds again, worse than before.", ex: "Dragon hunts hero" },
      { id: "culmination",name: "Main Culmination",                pct: 12, act: "climax", threeAct: 3, guide: "The crisis point just before the climax.", ex: "Final plan forms" },
      { id: "climax",     name: "Climax & Resolution",             pct: 13, act: "fall",   threeAct: 3, guide: "The conflict is decided, and the new world is shown.", ex: "Dragon defeated finally" },
    ],
  },
  {
    id: "weiland",
    name: "Weiland's Structure",
    blurb: "A novelist's refinement of the three-act paradigm, with 'pinch points' keeping the antagonist's threat visible throughout.",
    beats: [
      { id: "hook",      name: "Hook",               pct: 3,  act: "setup",  threeAct: 1, guide: "A small opening scene that shows the protagonist's normal world and a hint of their flaw.", ex: "Farmer avoids conflict" },
      { id: "inciting",  name: "Inciting Event",      pct: 9,  act: "setup",  threeAct: 1, guide: "The event that sets the story in motion, though the protagonist doesn't yet fully engage.", ex: "Dragon attacks village" },
      { id: "plot-point-1", name: "First Plot Point", pct: 13, act: "setup",  threeAct: 1, guide: "The protagonist commits, crossing into the main conflict for good.", ex: "Hero grabs sword" },
      { id: "pinch-1",   name: "First Pinch Point",   pct: 12, act: "rise",   threeAct: 2, guide: "A reminder of the antagonist's power — no direct confrontation yet, just a taste of the threat.", ex: "Dragon's shadow passes" },
      { id: "midpoint",  name: "Midpoint",            pct: 13, act: "rise",   threeAct: 2, guide: "The protagonist moves from reacting to acting, often via a piece of new information.", ex: "Learns dragon's weakness" },
      { id: "pinch-2",   name: "Second Pinch Point",  pct: 12, act: "climax", threeAct: 2, guide: "Another reminder of the antagonist's power, now sharper — things are worse than the first pinch point.", ex: "Dragon burns fields" },
      { id: "plot-point-3", name: "Third Plot Point", pct: 13, act: "climax", threeAct: 3, guide: "A low point — often a false defeat — that forces the protagonist's final resolve.", ex: "Ally is lost" },
      { id: "climax",    name: "Climax",              pct: 15, act: "climax", threeAct: 3, guide: "The final confrontation, where the protagonist's arc and the plot's conflict resolve together.", ex: "Duels dragon alone" },
      { id: "resolution",name: "Resolution",          pct: 10, act: "fall",   threeAct: 3, guide: "The new normal, shown rather than explained.", ex: "Village rebuilds anew" },
    ],
  },
  {
    id: "truby-22",
    name: "Truby's 22 Steps",
    blurb: "John Truby's granular structure, built around a moral argument the protagonist is forced to test.",
    beats: [
      { id: "self-rev-preview", name: "Self-Revelation, Need, Desire", pct: 4, act: "setup", threeAct: 1, guide: "A glimpse of the change to come — often not shown to the audience directly, but present as the story's underlying shape.", ex: "Hero fears failure" },
      { id: "ghost",     name: "Ghost and Story World",   pct: 4, act: "setup", threeAct: 1, guide: "The wound in the protagonist's past, and the ordinary world shaped around it.", ex: "Village fears dragons" },
      { id: "weakness",  name: "Weakness and Need",       pct: 4, act: "setup", threeAct: 1, guide: "The flaw the protagonist must overcome, and the deeper psychological need beneath their surface want.", ex: "Hero avoids conflict" },
      { id: "inciting",  name: "Inciting Event",          pct: 6, act: "setup", threeAct: 1, guide: "The event that starts the story's action.", ex: "Dragon attacks village" },
      { id: "desire",    name: "Desire",                  pct: 4, act: "setup", threeAct: 1, guide: "The concrete goal the protagonist consciously pursues.", ex: "Vows to fight" },
      { id: "allies",    name: "Ally or Allies",          pct: 4, act: "rise",  threeAct: 1, guide: "Characters who help the protagonist pursue their desire.", ex: "Gathers loyal friends" },
      { id: "opponent",  name: "Opponent and/or Mystery", pct: 4, act: "rise",  threeAct: 1, guide: "The person or force blocking the protagonist, or the puzzle they must solve.", ex: "Dragon's lair hidden" },
      { id: "fake-ally", name: "Fake-Ally Opponent",      pct: 4, act: "rise",  threeAct: 2, guide: "An apparent ally who is secretly working against the protagonist.", ex: "Trusted friend betrays" },
      { id: "first-rev", name: "First Revelation and Decision", pct: 4, act: "rise", threeAct: 2, guide: "New information forces the protagonist to change their desire or approach.", ex: "Learns the truth" },
      { id: "plan",      name: "Plan",                    pct: 6, act: "rise",  threeAct: 2, guide: "How the protagonist intends to get what they want.", ex: "Devises a strategy" },
      { id: "opp-plan",  name: "Opponent's Plan and Main Counterattack", pct: 4, act: "rise", threeAct: 2, guide: "The opposition's own plan, and its first real counterattack.", ex: "Dragon strikes back" },
      { id: "drive",     name: "Drive",                   pct: 6, act: "climax", threeAct: 2, guide: "A concentrated string of actions as the protagonist pursues the plan.", ex: "Pushes toward goal" },
      { id: "attack-ally", name: "Attack by Ally",        pct: 4, act: "climax", threeAct: 2, guide: "Pressure or betrayal from within the protagonist's own camp.", ex: "Ally turns against" },
      { id: "apparent-defeat", name: "Apparent Defeat",   pct: 6, act: "climax", threeAct: 2, guide: "The protagonist appears to have lost completely.", ex: "All seems lost" },
      { id: "second-rev", name: "Second Revelation and Decision", pct: 4, act: "climax", threeAct: 2, guide: "Another revelation drives an even more determined, sometimes obsessive, pursuit.", ex: "Renews desperate resolve" },
      { id: "audience-rev", name: "Audience Revelation",  pct: 4, act: "climax", threeAct: 3, guide: "Information revealed to the audience that the characters don't yet know.", ex: "Reader learns truth" },
      { id: "third-rev", name: "Third Revelation and Decision", pct: 4, act: "climax", threeAct: 3, guide: "A final piece of information sets up the last decision before the climax.", ex: "Finds hidden weakness" },
      { id: "gate",      name: "Gate, Gauntlet, Visit to Death", pct: 6, act: "climax", threeAct: 3, guide: "The last, hardest obstacles standing between the protagonist and the final battle.", ex: "Faces near-certain death" },
      { id: "battle",    name: "Battle",                  pct: 6, act: "climax", threeAct: 3, guide: "The final confrontation between protagonist and opponent.", ex: "Duels dragon alone" },
      { id: "self-rev",  name: "Self-Revelation",         pct: 4, act: "fall",  threeAct: 3, guide: "The protagonist finally understands their own weakness and need.", ex: "Sees his flaw" },
      { id: "moral",     name: "Moral Decision",          pct: 4, act: "fall",  threeAct: 3, guide: "A final choice that proves the protagonist's change is real.", ex: "Chooses to forgive" },
      { id: "new-equilibrium", name: "New Equilibrium",   pct: 4, act: "fall",  threeAct: 3, guide: "The world settles into its new, changed state.", ex: "Village rebuilds, thrives" },
    ],
  },
  {
    id: "pixar-spine",
    name: "Pixar Story Spine",
    blurb: "The short-pitch template behind most Pixar shorts — status quo through consequence to a new normal.",
    beats: [
      { id: "once-upon", name: "Once Upon a Time", pct: 8,  act: "setup",  threeAct: 1, guide: "Establish who the protagonist is and the world they live in.", ex: "Farmer tends fields" },
      { id: "every-day", name: "Every Day",        pct: 12, act: "setup",  threeAct: 1, guide: "Show their routine — what 'normal' looks like before the story disturbs it.", ex: "Same chores, daily" },
      { id: "until-one-day", name: "Until One Day", pct: 10, act: "setup", threeAct: 1, guide: "The event that breaks the routine and starts the story.", ex: "Dragon attacks village" },
      { id: "because-1", name: "Because of That",  pct: 20, act: "rise",   threeAct: 2, guide: "The first consequence of that event, and what the protagonist does about it.", ex: "Hero seeks help" },
      { id: "because-2", name: "Because of That",  pct: 20, act: "rise",   threeAct: 2, guide: "A second consequence, escalating further — the chain of cause and effect keeps building.", ex: "Gathers allies, trains" },
      { id: "until-finally", name: "Until Finally", pct: 15, act: "climax", threeAct: 3, guide: "The climax — the final action that resolves the chain of consequences.", ex: "Duels dragon alone" },
      { id: "ever-since", name: "Ever Since Then", pct: 15, act: "fall",   threeAct: 3, guide: "The new normal, and how it differs from the routine at the start.", ex: "Village lives free" },
    ],
  },
  {
    id: "virgins-promise",
    name: "The Virgin's Promise",
    blurb: "Kim Hudson's structure for stories of creative or personal awakening against social conformity — a counterpart to the Hero's Journey.",
    beats: [
      { id: "dependent-world", name: "Dependent World",     pct: 8, act: "setup", threeAct: 1, guide: "The protagonist's world defines her value through duty and conformity — introduce that world and her place in it.", ex: "Bakery awaits inheritance" },
      { id: "price",     name: "Price of Conformity",       pct: 7, act: "setup", threeAct: 1, guide: "What she gives up, unconsciously, by staying safely inside the expected role.", ex: "Dreams quietly deferred" },
      { id: "opportunity", name: "Opportunity to Shine",    pct: 8, act: "setup", threeAct: 1, guide: "A chance appears to show a talent or truth the dependent world doesn't value.", ex: "Sees painting contest" },
      { id: "dresses-part", name: "Dresses the Part",       pct: 6, act: "rise",  threeAct: 1, guide: "She takes on a disguise or role that lets her explore the opportunity without fully committing.", ex: "Borrows a name" },
      { id: "secret-world", name: "Secret World",           pct: 9, act: "rise",  threeAct: 2, guide: "A hidden space where she can practice and grow without her dependent world watching.", ex: "Paints before dawn" },
      { id: "no-longer-fits", name: "No Longer Fits Her World", pct: 8, act: "rise", threeAct: 2, guide: "The gap between her secret self and her dependent-world self grows too wide to ignore.", ex: "Bakery feels smaller" },
      { id: "caught-shining", name: "Caught Shining",       pct: 9, act: "rise",  threeAct: 2, guide: "Her secret talent is discovered — or she's stopped just before it can be seen.", ex: "Father finds paintings" },
      { id: "gives-up", name: "Gives Up Her Dream",         pct: 8, act: "climax", threeAct: 2, guide: "Under pressure, she abandons the dream and returns fully to the dependent world.", ex: "Burns her canvases" },
      { id: "ally-helps", name: "Ally Helps Keep Dream Alive", pct: 8, act: "climax", threeAct: 2, guide: "Someone who believes in her keeps a door open, even after she's closed it herself.", ex: "Friend hides painting" },
      { id: "kingdom-chaos", name: "Kingdom in Chaos",      pct: 9, act: "climax", threeAct: 3, guide: "The dependent world itself destabilizes, proving it was never as safe as it promised.", ex: "Bakery nearly fails" },
      { id: "chooses-journey", name: "Chooses Her Journey", pct: 8, act: "climax", threeAct: 3, guide: "She actively chooses her own path, rather than drifting into it.", ex: "Reclaims her craft" },
      { id: "rages-reveals", name: "Rages or Reveals",      pct: 7, act: "fall",  threeAct: 3, guide: "She confronts the dependent world openly, on her own terms.", ex: "Shows work publicly" },
      { id: "wonder",    name: "Wonder",                    pct: 5, act: "fall",  threeAct: 3, guide: "A new equilibrium — her gift and her world coexist, changed for the better.", ex: "Bakery sells art" },
    ],
  },
  {
    id: "heroines-journey",
    name: "The Heroine's Journey",
    blurb: "Maureen Murdock's 10-stage arc away from and back toward the feminine — an inward counterpart to Campbell's outward quest.",
    beats: [
      { id: "separation", name: "Separation from the Feminine", pct: 8, act: "setup", threeAct: 1, guide: "The protagonist rejects traditionally feminine models — often modeled by her mother — as weak or limiting.", ex: "Leaves mother's house" },
      { id: "identification", name: "Identification with the Masculine", pct: 10, act: "setup", threeAct: 1, guide: "She adopts masculine-coded values (achievement, control) and finds mentors and allies who reward that.", ex: "Excels in law" },
      { id: "road-of-trials", name: "Road of Trials",       pct: 14, act: "setup", threeAct: 1, guide: "She proves herself against a series of challenges, on the terms of the world she's adopted.", ex: "Wins tough cases" },
      { id: "boon", name: "Finding the Boon of Success",    pct: 10, act: "rise", threeAct: 2, guide: "She achieves real, external success by those terms.", ex: "Made firm partner" },
      { id: "aridity", name: "Awakening to Spiritual Aridity", pct: 8, act: "rise", threeAct: 2, guide: "Success doesn't fill the hollow it was supposed to — something essential feels dead.", ex: "Feels strangely empty" },
      { id: "descent", name: "Initiation and Descent",      pct: 12, act: "rise", threeAct: 2, guide: "She turns inward, often prompted by a crisis, toward parts of herself she'd suppressed.", ex: "Returns to hometown" },
      { id: "yearning", name: "Yearning to Reconnect",      pct: 10, act: "climax", threeAct: 2, guide: "A pressing need to reclaim the feminine she once rejected.", ex: "Seeks out mother" },
      { id: "healing-split", name: "Healing the Mother/Daughter Split", pct: 10, act: "climax", threeAct: 3, guide: "Repairing the relationship — literal or symbolic — with the feminine model she once pushed away.", ex: "Mends old wound" },
      { id: "healing-masculine", name: "Healing the Wounded Masculine", pct: 9, act: "fall", threeAct: 3, guide: "The masculine side of herself is also healed — no longer armor, but a real strength.", ex: "Softens without weakness" },
      { id: "integration", name: "Integration",             pct: 9, act: "fall", threeAct: 3, guide: "Both sides are held together — a whole self, not a choice between them.", ex: "Leads with wholeness" },
    ],
  },
  {
    id: "todorov",
    name: "Todorov's Equilibrium Theory",
    blurb: "Tzvetan Todorov's five-stage model — the simplest shape there is: a state disrupted, then restored changed.",
    beats: [
      { id: "equilibrium",  name: "Equilibrium",              pct: 20, act: "setup",  threeAct: 1, guide: "The story's starting state — stable, though not necessarily happy.", ex: "Village lives peacefully" },
      { id: "disruption",   name: "Disruption",                pct: 15, act: "setup",  threeAct: 1, guide: "An event throws the equilibrium off balance.", ex: "Dragon attacks village" },
      { id: "recognition",  name: "Recognition of Disruption",  pct: 20, act: "rise",   threeAct: 2, guide: "Characters recognise that something has gone wrong and must be addressed.", ex: "Village names threat" },
      { id: "repair",       name: "Attempt to Repair",          pct: 30, act: "climax", threeAct: 2, guide: "An effort — often extended, often difficult — to fix the disruption.", ex: "Hero hunts dragon" },
      { id: "new-equilibrium", name: "New Equilibrium",         pct: 15, act: "fall",   threeAct: 3, guide: "A new stable state, changed by the story but stable again.", ex: "Village rebuilds, thrives" },
    ],
  },
  {
    id: "frame-narrative",
    name: "Frame Narrative",
    blurb: "A story bookended by another story — the frame opens and closes around an inner tale.",
    beats: [
      { id: "enter-frame",   name: "Enter Frame",                pct: 8,  act: "setup",  threeAct: 1, guide: "Introduce the outer story and its narrator or occasion for telling.", ex: "Traveler seeks shelter" },
      { id: "frame-setup",   name: "Frame Sets Up Inner Story",  pct: 7,  act: "setup",  threeAct: 1, guide: "The frame's own action creates a reason for the inner story to be told.", ex: "Elder offers tale" },
      { id: "inner-begins",  name: "Inner Story Begins",         pct: 15, act: "rise",   threeAct: 1, guide: "The inner story opens, with its own characters and stakes.", ex: "Old story begins" },
      { id: "inner-develops",name: "Inner Story Develops",       pct: 40, act: "rise",   threeAct: 2, guide: "The inner story carries most of the narrative weight, and its own arc.", ex: "Dragon attacks village" },
      { id: "inner-resolves",name: "Inner Story Resolves",       pct: 15, act: "climax", threeAct: 2, guide: "The inner story reaches its own resolution.", ex: "Dragon is defeated" },
      { id: "return-frame",  name: "Return to Frame",            pct: 7,  act: "climax", threeAct: 3, guide: "The narrative returns to the outer story, changed by having told the inner one.", ex: "Elder finishes tale" },
      { id: "frame-closes",  name: "Frame Closes",               pct: 8,  act: "fall",   threeAct: 3, guide: "The outer story concludes, often recontextualising the inner tale's meaning.", ex: "Traveler leaves changed" },
    ],
  },
  {
    id: "propp-31",
    name: "Propp's 31 Functions",
    blurb: "Vladimir Propp's morphology of the Russian folk tale — the most granular structure here, and the most folklore-specific.",
    beats: [
      { id: "absentation",   name: "Absentation",               pct: 2, act: "setup", threeAct: 1, guide: "A member of the family leaves the security of the home.", ex: "Father leaves home" },
      { id: "interdiction",  name: "Interdiction",              pct: 2, act: "setup", threeAct: 1, guide: "The hero is warned against some action.", ex: "Don't leave village" },
      { id: "violation",     name: "Violation",                 pct: 3, act: "setup", threeAct: 1, guide: "The interdiction is violated, opening the door to misfortune.", ex: "Hero leaves anyway" },
      { id: "reconnaissance",name: "Reconnaissance",             pct: 2, act: "setup", threeAct: 1, guide: "The villain makes an attempt to gather information.", ex: "Dragon scouts village" },
      { id: "delivery",      name: "Delivery",                  pct: 2, act: "setup", threeAct: 1, guide: "The villain gains information about their victim.", ex: "Dragon finds prey" },
      { id: "trickery",      name: "Trickery",                  pct: 3, act: "setup", threeAct: 1, guide: "The villain attempts to deceive the victim to take possession of them or their belongings.", ex: "Dragon lures hero" },
      { id: "complicity",    name: "Complicity",                pct: 2, act: "setup", threeAct: 1, guide: "The victim, unwittingly, helps the villain by taking the bait.", ex: "Hero takes bait" },
      { id: "villainy-lack", name: "Villainy / Lack",           pct: 5, act: "setup", threeAct: 1, guide: "The villain causes harm to a family member, or something is found to be lacking.", ex: "Dragon steals treasure" },
      { id: "mediation",     name: "Mediation",                 pct: 3, act: "setup", threeAct: 1, guide: "The misfortune or lack is made known; the hero is asked or sent to act.", ex: "Village calls hero" },
      { id: "counteraction", name: "Beginning Counteraction",    pct: 3, act: "rise",  threeAct: 2, guide: "The hero agrees to, or decides upon, counteraction.", ex: "Hero accepts quest" },
      { id: "departure",     name: "Departure",                 pct: 4, act: "rise",  threeAct: 2, guide: "The hero leaves home.", ex: "Hero leaves village" },
      { id: "donor-first",   name: "First Function of the Donor", pct: 4, act: "rise", threeAct: 2, guide: "The hero is tested, interrogated or attacked, preparing the way for receiving a magical agent or helper.", ex: "Old woman tests" },
      { id: "hero-reaction", name: "Hero's Reaction",           pct: 3, act: "rise",  threeAct: 2, guide: "The hero responds to the actions of the donor.", ex: "Hero passes test" },
      { id: "magical-agent",  name: "Receipt of a Magical Agent", pct: 4, act: "rise", threeAct: 2, guide: "The hero acquires the use of a magical agent.", ex: "Gains magic sword" },
      { id: "guidance",      name: "Guidance",                  pct: 3, act: "rise",  threeAct: 2, guide: "The hero is led to the object of the search.", ex: "Sword points onward" },
      { id: "struggle",      name: "Struggle",                  pct: 6, act: "rise",  threeAct: 2, guide: "The hero and villain do battle, directly or indirectly.", ex: "Battles the dragon" },
      { id: "branding",      name: "Branding",                  pct: 2, act: "rise",  threeAct: 2, guide: "The hero is marked — a wound, or the bestowal of a ring or scarf.", ex: "Scarred by fire" },
      { id: "victory",       name: "Victory",                   pct: 5, act: "rise",  threeAct: 2, guide: "The villain is defeated.", ex: "Dragon is defeated" },
      { id: "liquidation",   name: "Liquidation",               pct: 4, act: "rise",  threeAct: 2, guide: "The initial misfortune or lack is resolved.", ex: "Treasure is recovered" },
      { id: "return",        name: "Return",                    pct: 3, act: "climax", threeAct: 2, guide: "The hero sets off for home.", ex: "Hero heads home" },
      { id: "pursuit",       name: "Pursuit",                   pct: 3, act: "climax", threeAct: 2, guide: "The hero is pursued.", ex: "Dragon's kin chase" },
      { id: "rescue",        name: "Rescue",                    pct: 3, act: "climax", threeAct: 2, guide: "The hero is rescued from pursuit.", ex: "Ally saves hero" },
      { id: "unrecognized",  name: "Unrecognized Arrival",      pct: 2, act: "climax", threeAct: 3, guide: "The hero arrives home or elsewhere, unrecognized.", ex: "Returns in disguise" },
      { id: "unfounded",     name: "Unfounded Claims",          pct: 2, act: "climax", threeAct: 3, guide: "A false hero presents unfounded claims to the reward.", ex: "Imposter claims credit" },
      { id: "difficult-task", name: "Difficult Task",           pct: 4, act: "climax", threeAct: 3, guide: "A difficult task is proposed to the hero.", ex: "Must prove himself" },
      { id: "solution",      name: "Solution",                  pct: 4, act: "climax", threeAct: 3, guide: "The task is resolved.", ex: "Shows the scar" },
      { id: "propp-recognition", name: "Recognition",           pct: 3, act: "climax", threeAct: 3, guide: "The hero is recognized, often by the mark from Branding.", ex: "Village recognizes hero" },
      { id: "exposure",      name: "Exposure",                  pct: 3, act: "climax", threeAct: 3, guide: "The false hero or villain is exposed.", ex: "Imposter is exposed" },
      { id: "transfiguration", name: "Transfiguration",         pct: 2, act: "fall",  threeAct: 3, guide: "The hero is given a new appearance.", ex: "Hero looks radiant" },
      { id: "punishment",    name: "Punishment",                pct: 3, act: "fall",  threeAct: 3, guide: "The villain, or the false hero, is punished.", ex: "Imposter is banished" },
      { id: "wedding",       name: "Wedding",                   pct: 6, act: "fall",  threeAct: 3, guide: "The hero marries and/or ascends the throne.", ex: "Hero weds, rules" },
    ],
  },
];

export const structureById = id => STRUCTURES.find(s => s.id === id) || STRUCTURES[0];
